<?xml version="1.0" encoding="utf-8"?><Database Name="Sqllhdb" Class="EntranceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=F01\SQLEXPRESS;Initial Catalog=Sqllhdb;Persist Security Info=True;User ID=sa" SettingsObjectName="ExportDomain.Properties.Settings" SettingsPropertyName="SqllhdbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Entrance" Member="Entrances">
    <Type Name="Entrance">
      <Column Name="EntranceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="UrlA" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
</Database>