#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportDomain.Entrance
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sqllhdb")]
	public partial class EntranceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public EntranceDataContext() : 
				base(global::ExportDomain.Properties.Settings.Default.SqllhdbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EntranceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntranceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntranceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntranceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Entrance> Entrances
		{
			get
			{
				return this.GetTable<Entrance>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Entrance")]
	public partial class Entrance
	{
		
		private int _EntranceID;
		
		private string _Text;
		
		private string _UrlA;
		
		public Entrance()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntranceID", DbType="Int NOT NULL")]
		public int EntranceID
		{
			get
			{
				return this._EntranceID;
			}
			set
			{
				if ((this._EntranceID != value))
				{
					this._EntranceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(150)")]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this._Text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlA", DbType="NVarChar(200)")]
		public string UrlA
		{
			get
			{
				return this._UrlA;
			}
			set
			{
				if ((this._UrlA != value))
				{
					this._UrlA = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
