//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmActivityMarketing
    {
        public int ActivityMarketingID { get; set; }
        public int LeadID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int ContentID { get; set; }
        public string Contents { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> FollowupDate { get; set; }
        public bool Done { get; set; }
    
        public virtual CrmLeadContentsMarketing CrmLeadContentsMarketing { get; set; }
        public virtual CrmLead CrmLead { get; set; }
    }
}
