//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmLeadRateRepeatCustomer
    {
        public CrmLeadRateRepeatCustomer()
        {
            this.CrmLeadRatings = new HashSet<CrmLeadRating>();
        }
    
        public int RepeatCustomerID { get; set; }
        public string Name { get; set; }
        public int Score { get; set; }
    
        public virtual ICollection<CrmLeadRating> CrmLeadRatings { get; set; }
    }
}
