//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmLeadDocument
    {
        public int DocID { get; set; }
        public int LeadID { get; set; }
        public string DocTitle { get; set; }
        public string DocHyperlink { get; set; }
        public int UploadBy { get; set; }
        public Nullable<System.DateTime> UploadAt { get; set; }
        public string View1 { get; set; }
    
        public virtual CrmLead CrmLead { get; set; }
    }
}
