//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmLeadCustomer
    {
        public int LeadCustomerID { get; set; }
        public int LeadID { get; set; }
        public int RowID { get; set; }
    
        public virtual CrmLead CrmLead { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
