//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmLeadAddress
    {
        public CrmLeadAddress()
        {
            this.CrmLeads = new HashSet<CrmLead>();
        }
    
        public int AddressID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Country { get; set; }
        public string PoBox { get; set; }
        public string MarjorIntersection { get; set; }
        public string Longitude { get; set; }
        public string Lattitude { get; set; }
    
        public virtual ICollection<CrmLead> CrmLeads { get; set; }
    }
}
