//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmLeadRating
    {
        public CrmLeadRating()
        {
            this.CrmLeads = new HashSet<CrmLead>();
        }
    
        public int RatingID { get; set; }
        public int Rate { get; set; }
        public int AuthorityID { get; set; }
        public int BudgetID { get; set; }
        public int InterActionID { get; set; }
        public int GrowthID { get; set; }
        public int RepeatCustomerID { get; set; }
        public int TimeframeID { get; set; }
    
        public virtual CrmLeadRateAuthority CrmLeadRateAuthority { get; set; }
        public virtual CrmLeadRateBudget CrmLeadRateBudget { get; set; }
        public virtual CrmLeadRateGrowth CrmLeadRateGrowth { get; set; }
        public virtual CrmLeadRateInterAction CrmLeadRateInterAction { get; set; }
        public virtual CrmLeadRateRepeatCustomer CrmLeadRateRepeatCustomer { get; set; }
        public virtual CrmLeadRateTimeframe CrmLeadRateTimeframe { get; set; }
        public virtual ICollection<CrmLead> CrmLeads { get; set; }
    }
}
