//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmLeadContact
    {
        public CrmLeadContact()
        {
            this.CrmLeads = new HashSet<CrmLead>();
        }
    
        public int ContactID { get; set; }
        public int LeadID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Position { get; set; }
        public string Hornorific { get; set; }
        public string HomePhone { get; set; }
        public string BusinessPhone { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public bool EmailOptIn { get; set; }
        public bool OkToCall { get; set; }
        public int CustomerContactID { get; set; }
        public string Remark { get; set; }
        public bool IsMainContact { get; set; }
    
        public virtual CUSTOMER_CONTACT CUSTOMER_CONTACT { get; set; }
        public virtual ICollection<CrmLead> CrmLeads { get; set; }
        public virtual CrmLead CrmLead { get; set; }
    }
}
