//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmLeadContentsMarketing
    {
        public CrmLeadContentsMarketing()
        {
            this.CrmActivityMarketings = new HashSet<CrmActivityMarketing>();
        }
    
        public int ContentID { get; set; }
        public string Contents { get; set; }
        public string Note { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<CrmActivityMarketing> CrmActivityMarketings { get; set; }
    }
}
