//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmStage
    {
        public CrmStage()
        {
            this.CrmLeads = new HashSet<CrmLead>();
        }
    
        public int StageID { get; set; }
        public string StageName { get; set; }
    
        public virtual ICollection<CrmLead> CrmLeads { get; set; }
    }
}
