//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_CONTACT
    {
        public CUSTOMER_CONTACT()
        {
            this.Sales_JobMasterList_Customer = new HashSet<Sales_JobMasterList_Customer>();
            this.CrmLeadContacts = new HashSet<CrmLeadContact>();
        }
    
        public int CONTACT_ID { get; set; }
        public int CUSTOMER_ROWID { get; set; }
        public string CONTACT_FIRST_NAME { get; set; }
        public string CONTACT_LAST_NAME { get; set; }
        public string CONTACT_POSITION { get; set; }
        public string CONTACT_HONORIFIC { get; set; }
        public string CONTACT_PHONE { get; set; }
        public string CONTACT_FAX { get; set; }
        public string CONTACT_MOBILE { get; set; }
        public string CONTACT_EMAIL { get; set; }
        public bool CONTACT_ACTIVE { get; set; }
        public bool isAccountPayable { get; set; }
        public bool isSiteContact { get; set; }
        public bool isProjectManager { get; set; }
    
        public virtual ICollection<Sales_JobMasterList_Customer> Sales_JobMasterList_Customer { get; set; }
        public virtual ICollection<CrmLeadContact> CrmLeadContacts { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
