//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDomain.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CustomerDbEntities : DbContext
    {
        public CustomerDbEntities()
            : base("name=CustomerDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer_Activity> Customer_Activity { get; set; }
        public virtual DbSet<CUSTOMER_CONTACT> CUSTOMER_CONTACT { get; set; }
        public virtual DbSet<Sales_JobMasterList_Customer> Sales_JobMasterList_Customer { get; set; }
        public virtual DbSet<CrmActivityMarketing> CrmActivityMarketings { get; set; }
        public virtual DbSet<CrmLeadAddress> CrmLeadAddresses { get; set; }
        public virtual DbSet<CrmLeadContact> CrmLeadContacts { get; set; }
        public virtual DbSet<CrmLeadContentsMarketing> CrmLeadContentsMarketings { get; set; }
        public virtual DbSet<CrmLeadContentsProgress> CrmLeadContentsProgresses { get; set; }
        public virtual DbSet<CrmLeadCustomer> CrmLeadCustomers { get; set; }
        public virtual DbSet<CrmLeadDocument> CrmLeadDocuments { get; set; }
        public virtual DbSet<CrmLeadHistoryEvent> CrmLeadHistoryEvents { get; set; }
        public virtual DbSet<CrmLeadOther> CrmLeadOthers { get; set; }
        public virtual DbSet<CrmLeadRateAuthority> CrmLeadRateAuthorities { get; set; }
        public virtual DbSet<CrmLeadRateBudget> CrmLeadRateBudgets { get; set; }
        public virtual DbSet<CrmLeadRateGrowth> CrmLeadRateGrowths { get; set; }
        public virtual DbSet<CrmLeadRateInterAction> CrmLeadRateInterActions { get; set; }
        public virtual DbSet<CrmLeadRateRepeatCustomer> CrmLeadRateRepeatCustomers { get; set; }
        public virtual DbSet<CrmLeadRateTimeframe> CrmLeadRateTimeframes { get; set; }
        public virtual DbSet<CrmLeadRating> CrmLeadRatings { get; set; }
        public virtual DbSet<CrmStage> CrmStages { get; set; }
        public virtual DbSet<FW_QUOTE_IC> FW_QUOTE_IC { get; set; }
        public virtual DbSet<FW_QUOTE_SOURCE> FW_QUOTE_SOURCE { get; set; }
        public virtual DbSet<CrmLead> CrmLeads { get; set; }
        public virtual DbSet<CrmLeadHistory> CrmLeadHistories { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<FW_Employees> FW_Employees { get; set; }
    }
}
