//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public CUSTOMER()
        {
            this.CrmLeadCustomers = new HashSet<CrmLeadCustomer>();
            this.Customer_Activity = new HashSet<Customer_Activity>();
            this.CUSTOMER_CONTACT = new HashSet<CUSTOMER_CONTACT>();
            this.Sales_JobMasterList_Customer = new HashSet<Sales_JobMasterList_Customer>();
        }
    
        public int ROWID { get; set; }
        public string ID { get; set; }
        public string NAME { get; set; }
        public string LEGAL_NAME { get; set; }
        public bool LEGALNAME_SAMEAS_NAME { get; set; }
        public string ADDR_1 { get; set; }
        public string ADDR_2 { get; set; }
        public string ADDR_3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIPCODE { get; set; }
        public string COUNTRY { get; set; }
        public string poBox { get; set; }
        public string Intersection { get; set; }
        public bool NorthWest { get; set; }
        public bool NorthEast { get; set; }
        public bool SouthWest { get; set; }
        public bool SouthEast { get; set; }
        public double Lat { get; set; }
        public double Lng { get; set; }
        public string TERRITORY { get; set; }
        public string locationCode { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public Nullable<System.DateTime> OPEN_DATE { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string CURRENCY_ID { get; set; }
        public short termID { get; set; }
        public Nullable<short> depositRequired { get; set; }
        public Nullable<System.DateTime> FirstContractDate { get; set; }
        public short selectType { get; set; }
        public int HEADOFFICE { get; set; }
        public int SalesID { get; set; }
        public int Sa1ID { get; set; }
        public string TempSales { get; set; }
        public string TempSA1 { get; set; }
        public int IndustryID { get; set; }
        public int Source { get; set; }
        public int ReferbyEmployee { get; set; }
        public int Referby { get; set; }
        public string ReferByText { get; set; }
        public int BelongTo { get; set; }
        public bool DeemedAsOld { get; set; }
        public int PreviousSalesID { get; set; }
        public Nullable<System.DateTime> CommissionFirstInvoiceDate { get; set; }
        public bool IsReactive { get; set; }
        public bool IsNewLineOfHouseAccount { get; set; }
    
        public virtual ICollection<CrmLeadCustomer> CrmLeadCustomers { get; set; }
        public virtual ICollection<Customer_Activity> Customer_Activity { get; set; }
        public virtual ICollection<CUSTOMER_CONTACT> CUSTOMER_CONTACT { get; set; }
        public virtual FW_QUOTE_IC FW_QUOTE_IC { get; set; }
        public virtual FW_QUOTE_SOURCE FW_QUOTE_SOURCE { get; set; }
        public virtual ICollection<Sales_JobMasterList_Customer> Sales_JobMasterList_Customer { get; set; }
        public virtual FW_Employees FW_Employees { get; set; }
    }
}
