//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionInforInvoice
    {
        public int RowID { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.DateTime ZeroDate { get; set; }
        public double SalesAmount { get; set; }
        public string CustomerID { get; set; }
        public string SalesRepID { get; set; }
        public string CustomerName { get; set; }
        public int PrintingEmployeeID { get; set; }
        public int MisInvoiceID { get; set; }
        public int Status { get; set; }
    
        public virtual Sales_JobMasterList_Invoice Sales_JobMasterList_Invoice { get; set; }
    }
}
