//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_OnGoingContract
    {
        public int ID { get; set; }
        public int JobID { get; set; }
        public string SalesName { get; set; }
        public string JobNumber { get; set; }
        public string JobTitle { get; set; }
        public System.DateTime TargetDate { get; set; }
        public Nullable<System.DateTime> IssueDateOfLastWorkorder { get; set; }
        public int DaysBetweenLastWorkorAndTargetDate { get; set; }
        public double ContractAmount { get; set; }
        public double IssuedWorkorderAmount { get; set; }
        public Nullable<int> IssuedWorkorderCount { get; set; }
        public double ToBeIssuedWorkorderAmount { get; set; }
        public double WoFinishedAmount { get; set; }
        public double WoOnGoingAmount { get; set; }
        public Nullable<double> WoOnGoingAmountShop { get; set; }
        public Nullable<double> WoOnGoingAmountInstallation { get; set; }
        public Nullable<double> WoOnGoingAmountLocalInstaller { get; set; }
        public Nullable<double> InvoicedAmount { get; set; }
        public int SalesID { get; set; }
        public int PcID { get; set; }
        public int QuoteRevID { get; set; }
        public int InstallToCustomerID { get; set; }
        public int PrintingEmployeeID { get; set; }
        public int ReportEmployeeID { get; set; }
        public int ReportEmployeeTeamID { get; set; }
        public string Problem { get; set; }
        public string IssuedWorkorderNumbers { get; set; }
        public string FinishedWorkorderNumbers { get; set; }
        public string OnGoingWorkorderNumbers { get; set; }
        public string Note { get; set; }
        public int WeekNumber { get; set; }
        public int ColourCode { get; set; }
        public Nullable<double> SignedContractAmount { get; set; }
        public Nullable<double> AdminFee { get; set; }
        public Nullable<double> SignedContractPlusAdminFee { get; set; }
    
        public virtual Sales_JobMasterList Sales_JobMasterList { get; set; }
    }
}
