//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_ProjectWip
    {
        public long ID { get; set; }
        public int PrintingEmployeeID { get; set; }
        public int JobID { get; set; }
        public int ReportEmployeeID { get; set; }
        public int ReportEmployeeTeamID { get; set; }
        public string JobTitle { get; set; }
        public int InstallToCustomerID { get; set; }
        public string InstallToAddress { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public int QuoteRevID { get; set; }
        public Nullable<decimal> ContractAmount { get; set; }
        public string CollectingInfo { get; set; }
        public int OpID { get; set; }
        public string Remark { get; set; }
    
        public virtual Sales_JobMasterList Sales_JobMasterList { get; set; }
    }
}
