//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_ProjectStage
    {
        public long ID { get; set; }
        public int PrintingEmployeeID { get; set; }
        public int ReportEmployeeID { get; set; }
        public Nullable<int> ReportEmployeeTeamID { get; set; }
        public int JobID { get; set; }
        public string JobTitle { get; set; }
        public int InstallToCustomerID { get; set; }
        public string InstallToAddress { get; set; }
        public System.DateTime TargetDate { get; set; }
        public Nullable<System.DateTime> EstimationSubmit { get; set; }
        public Nullable<System.DateTime> EstimationReceived { get; set; }
        public bool IsBidding { get; set; }
        public int QuoteRevID { get; set; }
        public int QuoteVersion { get; set; }
        public Nullable<decimal> QuoteAmount { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> QuotationSendDate { get; set; }
        public Nullable<System.DateTime> LastQuotationFollowUpDate { get; set; }
        public string LastQuotationFollowUpContent { get; set; }
        public string Result { get; set; }
        public string ResultNote { get; set; }
    
        public virtual Sales_JobMasterList Sales_JobMasterList { get; set; }
    }
}
