//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_ProjectWipDetails
    {
        public long ID { get; set; }
        public int PrintingEmployeeID { get; set; }
        public int JobID { get; set; }
        public int RowType { get; set; }
        public string PreDrawing { get; set; }
        public Nullable<System.DateTime> GraphicDrawingPreparation { get; set; }
        public Nullable<System.DateTime> StructuralDrawingPreparation { get; set; }
        public Nullable<System.DateTime> SiteCheck { get; set; }
        public Nullable<System.DateTime> SampleApproval { get; set; }
        public Nullable<System.DateTime> ClientApproval { get; set; }
        public Nullable<System.DateTime> LandlordApproval { get; set; }
        public Nullable<System.DateTime> EngineeringStamp { get; set; }
        public Nullable<System.DateTime> PermitApply { get; set; }
        public Nullable<System.DateTime> StakeoutApply { get; set; }
        public Nullable<System.DateTime> PermitWaiver { get; set; }
        public Nullable<System.DateTime> WorkorderIssuedDate { get; set; }
        public Nullable<double> CompletionOfWorkorder { get; set; }
        public Nullable<System.DateTime> WorkorderDeadline { get; set; }
        public Nullable<System.DateTime> OSID { get; set; }
    
        public virtual Sales_JobMasterList Sales_JobMasterList { get; set; }
    }
}
