//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FW_Employees
    {
        public FW_Employees()
        {
            this.Sales_Dispatching = new HashSet<Sales_Dispatching>();
            this.Sales_JobMasterList = new HashSet<Sales_JobMasterList>();
            this.Sales_JobMasterList_WO = new HashSet<Sales_JobMasterList_WO>();
        }
    
        public int EmployeeNumber { get; set; }
        public string NickName { get; set; }
        public string Department { get; set; }
        public bool Active { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string DisplayName { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> SINCardNumber { get; set; }
        public string EmailAddress { get; set; }
        public string EmergencyContactPerson { get; set; }
        public string EmergencyContactNumber1 { get; set; }
        public string EmergencyContactNumber2 { get; set; }
        public string Position { get; set; }
        public Nullable<int> paytype { get; set; }
        public Nullable<int> payrate { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyCellphone { get; set; }
        public string Extension { get; set; }
        public string Performance { get; set; }
        public string History { get; set; }
        public string Training { get; set; }
        public string NumberInfor { get; set; }
        public string Password { get; set; }
        public string Roles { get; set; }
        public string UserName { get; set; }
        public string Sa1Name { get; set; }
        public string Sa2Name { get; set; }
        public string SalesName { get; set; }
        public string Notes { get; set; }
        public int PayrollNumber { get; set; }
        public string DepartmentID { get; set; }
        public bool ncrEnable { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<bool> response { get; set; }
        public byte[] signature { get; set; }
        public int dID { get; set; }
        public int Team { get; set; }
        public bool isLeadHand { get; set; }
        public bool isAE { get; set; }
        public int Role { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> StartWorkingDate { get; set; }
        public Nullable<System.DateTime> EndWorkingDate1 { get; set; }
        public Nullable<System.DateTime> ReturnToWorkDate { get; set; }
        public Nullable<System.DateTime> EndWorkingDate2 { get; set; }
        public short SelectType { get; set; }
        public string IsProbation { get; set; }
        public bool IsInProbation { get; set; }
        public int ProbationPeriod { get; set; }
        public bool ShowOnInputHour { get; set; }
        public bool IsFake { get; set; }
        public bool IsShowOnPerformanceReport { get; set; }
        public bool ShowOnCrmPage1 { get; set; }
        public bool ShowOnCommissionPage1 { get; set; }
        public bool ShowOnCommissionPage2 { get; set; }
        public bool CrmLeadOwner { get; set; }
        public bool CrmLeadAE { get; set; }
        public bool CrmLeadSelectAeEnable { get; set; }
        public bool IsAdminTaskSelected { get; set; }
        public bool IsShowOnSubdepartmentSchedule { get; set; }
        public bool IsMtoAwared { get; set; }
        public int ProcedureGroupID { get; set; }
        public int EntityID { get; set; }
        public bool IsSubcontract { get; set; }
    
        public virtual ICollection<Sales_Dispatching> Sales_Dispatching { get; set; }
        public virtual ICollection<Sales_JobMasterList> Sales_JobMasterList { get; set; }
        public virtual ICollection<Sales_JobMasterList_WO> Sales_JobMasterList_WO { get; set; }
    }
}
