//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FW_WORK_ORDER
    {
        public FW_WORK_ORDER()
        {
            this.CR_Workorder = new HashSet<CR_Workorder>();
        }
    
        public string WORKORDER_NUMBER { get; set; }
        public string TITLE { get; set; }
        public string ITEM_NAME { get; set; }
        public Nullable<System.DateTime> JOB_DEADLINE { get; set; }
        public string SALES { get; set; }
        public string SALES_ASSISTANT_1 { get; set; }
        public string SALES_ASSISTANT_2 { get; set; }
        public string JOB_TYPE { get; set; }
        public Nullable<double> QUOTATION_EST_WORKSHOP { get; set; }
        public Nullable<double> QUOTATION_EST_METAL { get; set; }
        public Nullable<double> QUOTATION_EST_PLASTIC_A { get; set; }
        public Nullable<double> QUOTATION_EST_PLASTIC_B { get; set; }
        public Nullable<double> QUOTATION_EST_PAINTING { get; set; }
        public Nullable<double> QUOTATION_EST_RA3 { get; set; }
        public Nullable<double> QUOTATION_EST_INSTALLATION { get; set; }
        public Nullable<double> QUOTATION_EST_SITECHECK { get; set; }
        public Nullable<double> QUOTATION_EST_STRUCTURAL { get; set; }
        public Nullable<double> QUOTATION_EST_ARTROOM { get; set; }
        public Nullable<double> QUOTATION_EST_WSERVICE { get; set; }
        public Nullable<double> CONTRACT_AMOUNT { get; set; }
        public Nullable<double> EXTRA_WORKSHOP { get; set; }
        public Nullable<double> EXTRA_INSTALLATION { get; set; }
        public Nullable<double> EXTRA_ARTROOM { get; set; }
        public string STATUS_WORKSHOP { get; set; }
        public string STATUS_INSTALLATION { get; set; }
        public string STATUS_ARTROOM { get; set; }
        public Nullable<System.DateTime> FINISHED_DATE_ARTROOM { get; set; }
        public Nullable<System.DateTime> FINISHED_DATE_WORKSHOP { get; set; }
        public Nullable<System.DateTime> FINISHED_DATE_INSTALLATION { get; set; }
        public Nullable<System.DateTime> CHANGED_JOB_DEADLINE { get; set; }
        public string INSTALLATION_TIME { get; set; }
        public Nullable<int> JOB_TYPE_ID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public string POST_CODE { get; set; }
        public bool Redo { get; set; }
        public bool Rush { get; set; }
        public bool Revise { get; set; }
        public int woID { get; set; }
        public int WorkorderStatus { get; set; }
        public Nullable<double> Workload { get; set; }
        public string SubDepartmentStatus { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ProductionScheduleDate { get; set; }
        public Nullable<System.DateTime> ProductionFinishDate { get; set; }
        public Nullable<System.DateTime> Schedule1 { get; set; }
        public Nullable<System.DateTime> Schedule2 { get; set; }
        public Nullable<System.DateTime> Schedule3 { get; set; }
        public Nullable<System.DateTime> Schedule4 { get; set; }
        public Nullable<System.DateTime> Schedule5 { get; set; }
        public int Finish1 { get; set; }
        public int Finish2 { get; set; }
        public int Finish3 { get; set; }
        public int Finish4 { get; set; }
        public int Finish5 { get; set; }
        public int IsJobCostingRequired { get; set; }
        public int InstallationSubDeptID { get; set; }
        public Nullable<double> OriginalEst { get; set; }
        public double Variance { get; set; }
        public string VarianceReason { get; set; }
        public int VarianceStatusID { get; set; }
        public Nullable<System.DateTime> ManagerFinishDate { get; set; }
        public int EstInputStatusID { get; set; }
        public Nullable<System.DateTime> EstInputStatusLastUpdateTime { get; set; }
        public int EstInputStatusLastUpdateBy { get; set; }
        public int ReviseVer { get; set; }
        public bool IsMisc { get; set; }
    
        public virtual ICollection<CR_Workorder> CR_Workorder { get; set; }
        public virtual Sales_JobMasterList_WO Sales_JobMasterList_WO { get; set; }
    }
}
