//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Quote_Item = new HashSet<Quote_Item>();
        }
    
        public int ProductID { get; set; }
        public int CategoryID { get; set; }
        public string ProductName { get; set; }
        public int OptionID1 { get; set; }
        public int OptionID2 { get; set; }
        public int OptionID3 { get; set; }
        public bool Active { get; set; }
        public int SupplyAndInstall { get; set; }
        public int SupplyOnly { get; set; }
        public decimal BasePrice { get; set; }
    
        public virtual ICollection<Quote_Item> Quote_Item { get; set; }
    }
}
