//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectModelDbEntities : DbContext
    {
        public ProjectModelDbEntities()
            : base("name=ProjectModelDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Sales_JobMasterList_Invoice_Workorder> Sales_JobMasterList_Invoice_Workorder { get; set; }
        public DbSet<Sales_Wip> Sales_Wip { get; set; }
        public DbSet<tblWipTask> tblWipTasks { get; set; }
        public DbSet<Invoice_Item> Invoice_Item { get; set; }
        public DbSet<Sales_SpecialMaterial> Sales_SpecialMaterial { get; set; }
        public DbSet<Sales_SpecialMaterialRequest> Sales_SpecialMaterialRequest { get; set; }
        public DbSet<WO_Shipping> WO_Shipping { get; set; }
        public DbSet<WO_ShippingItem> WO_ShippingItem { get; set; }
        public DbSet<WO_Item> WO_Item { get; set; }
        public DbSet<Sales_JobMasterList_QuoteRev> Sales_JobMasterList_QuoteRev { get; set; }
        public DbSet<Sales_JobStatusTable> Sales_JobStatusTable { get; set; }
        public DbSet<CR_Commission> CR_Commission { get; set; }
        public DbSet<CR_Commission_InvoiceList> CR_Commission_InvoiceList { get; set; }
        public DbSet<CommissionInforInvoice> CommissionInforInvoices { get; set; }
        public DbSet<Sales_JobMaster_Invoice_CommissionOnHold> Sales_JobMaster_Invoice_CommissionOnHold { get; set; }
        public DbSet<Sales_JobMasterList_Invoice> Sales_JobMasterList_Invoice { get; set; }
        public DbSet<Sales_WipPublic> Sales_WipPublic { get; set; }
        public DbSet<FW_JOB_TYPE> FW_JOB_TYPE { get; set; }
        public DbSet<CR_ProjectStage> CR_ProjectStage { get; set; }
        public DbSet<CR_ProjectWip> CR_ProjectWip { get; set; }
        public DbSet<CR_ProjectWipDetails> CR_ProjectWipDetails { get; set; }
        public DbSet<CR_WorkOnHandForAccounting> CR_WorkOnHandForAccounting { get; set; }
        public DbSet<Sales_JobMasterList_Customer> Sales_JobMasterList_Customer { get; set; }
        public DbSet<Sales_Dispatching> Sales_Dispatching { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Quote_Item> Quote_Item { get; set; }
        public DbSet<CR_OnGoingContract> CR_OnGoingContract { get; set; }
        public DbSet<Sales_JobMasterList_WO> Sales_JobMasterList_WO { get; set; }
        public DbSet<Sales_JobMasterList_WO_Note> Sales_JobMasterList_WO_Note { get; set; }
        public DbSet<CR_Workorder> CR_Workorder { get; set; }
        public DbSet<Sales_JobMasterList> Sales_JobMasterList { get; set; }
        public DbSet<TblBiddingJobSource> TblBiddingJobSources { get; set; }
        public DbSet<TblBiddingJobType> TblBiddingJobTypes { get; set; }
        public DbSet<Sales_JobMasterList_QuoteFollow> Sales_JobMasterList_QuoteFollow { get; set; }
        public DbSet<TblQuoteFollowupStatu> TblQuoteFollowupStatus { get; set; }
        public DbSet<Sales_JobMaster_BiddingJob> Sales_JobMaster_BiddingJob { get; set; }
        public DbSet<FW_WORK_ORDER> FW_WORK_ORDER { get; set; }
        public DbSet<FW_Employees> FW_Employees { get; set; }
    }
}
