//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote_Item
    {
        public int quoteItemID { get; set; }
        public int quoteRevID { get; set; }
        public int estItemID { get; set; }
        public short qiPrintOrder { get; set; }
        public short quoteOption { get; set; }
        public bool isFinal { get; set; }
        public short supplyType { get; set; }
        public string qiItemTitle { get; set; }
        public string qiDescription { get; set; }
        public Nullable<decimal> qiAmount { get; set; }
        public Nullable<float> qiUnitPrice { get; set; }
        public short qiQty { get; set; }
        public Nullable<short> qiQtypc { get; set; }
        public string heightFromGround { get; set; }
        public Nullable<short> Requirement { get; set; }
        public string Position { get; set; }
        public string estItemNameText { get; set; }
        public string recordType { get; set; }
        public string quoteOptionText { get; set; }
        public string qiAmountText { get; set; }
        public int NameDetailsID { get; set; }
        public string SerialID { get; set; }
        public bool BySubcontractor { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Sales_JobMasterList_QuoteRev Sales_JobMasterList_QuoteRev { get; set; }
    }
}
