//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Wip
    {
        public long WipTaskID { get; set; }
        public int JobID { get; set; }
        public int estRevID { get; set; }
        public int quoteRevID { get; set; }
        public int woID { get; set; }
        public int invoiceID { get; set; }
        public short Priority { get; set; }
        public int ContentID { get; set; }
        public string Contents { get; set; }
        public short Status { get; set; }
        public Nullable<System.DateTime> ScheduleStartDate { get; set; }
        public Nullable<System.DateTime> ScheduleFinishDate { get; set; }
        public Nullable<System.DateTime> ActualFinishDate { get; set; }
        public string Note { get; set; }
        public int Responsible { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedAt { get; set; }
        public int LastUpdatedBy { get; set; }
    
        public virtual tblWipTask tblWipTask { get; set; }
        public virtual Sales_JobMasterList Sales_JobMasterList { get; set; }
    }
}
