//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_JobMasterList_QuoteFollow
    {
        public int ID { get; set; }
        public int jobID { get; set; }
        public System.DateTime fDate { get; set; }
        public string Note { get; set; }
        public int EmployeeID { get; set; }
        public bool IsEmailedToSales { get; set; }
        public int StatusID { get; set; }
    
        public virtual Sales_JobMasterList Sales_JobMasterList { get; set; }
        public virtual TblQuoteFollowupStatu TblQuoteFollowupStatu { get; set; }
    }
}
