//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_JobMasterList_WO_Note
    {
        public int id { get; set; }
        public int woID { get; set; }
        public Nullable<System.DateTime> rDate { get; set; }
        public string remark { get; set; }
        public bool InvoiceExclude { get; set; }
        public int NoteType { get; set; }
    
        public virtual Sales_JobMasterList_WO Sales_JobMasterList_WO { get; set; }
    }
}
