//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_JobStatusTable
    {
        public long jsrID { get; set; }
        public int jobID { get; set; }
        public Nullable<short> jobStatus { get; set; }
        public Nullable<System.DateTime> accomplishDate { get; set; }
        public Nullable<int> Performer { get; set; }
        public string Ref { get; set; }
        public string RefVersion { get; set; }
        public string Note { get; set; }
    
        public virtual Sales_JobMasterList Sales_JobMasterList { get; set; }
    }
}
