//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_SpecialMaterial
    {
        public int JobSpecialMaterialID { get; set; }
        public int JobID { get; set; }
        public int StatusID { get; set; }
        public string HandlingProcess { get; set; }
        public int LsmID { get; set; }
        public string Contents { get; set; }
        public string Unit { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> Count { get; set; }
        public Nullable<double> Amount { get; set; }
        public int Leadtime { get; set; }
        public Nullable<System.DateTime> ExpectingDeliveryTime { get; set; }
        public Nullable<System.DateTime> ActualReceivedTime { get; set; }
        public string Brand { get; set; }
        public string Specification { get; set; }
        public string Colour { get; set; }
        public int ItemNum { get; set; }
    
        public virtual Sales_JobMasterList Sales_JobMasterList { get; set; }
    }
}
