//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_JobMaster_Invoice_CommissionOnHold
    {
        public int RowID { get; set; }
        public int invoiceID { get; set; }
        public string invoiceNo { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> ZeroDate { get; set; }
        public string Remark { get; set; }
    
        public virtual Sales_JobMasterList_Invoice Sales_JobMasterList_Invoice { get; set; }
    }
}
