//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_JobMasterList_WO
    {
        public Sales_JobMasterList_WO()
        {
            this.Sales_JobMasterList_WO_Note = new HashSet<Sales_JobMasterList_WO_Note>();
            this.WO_Item = new HashSet<WO_Item>();
            this.WO_Shipping = new HashSet<WO_Shipping>();
            this.WO_ShippingItem = new HashSet<WO_ShippingItem>();
            this.FW_WORK_ORDER = new HashSet<FW_WORK_ORDER>();
        }
    
        public int woID { get; set; }
        public int jobID { get; set; }
        public int estRevID { get; set; }
        public short woType { get; set; }
        public Nullable<byte> woRev { get; set; }
        public Nullable<bool> woCurrent { get; set; }
        public string jobTitle { get; set; }
        public string WorkorderNumber { get; set; }
        public string findSiteAt { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public Nullable<System.DateTime> changedDeadLine { get; set; }
        public Nullable<System.DateTime> targetDate { get; set; }
        public Nullable<System.DateTime> issuedDate { get; set; }
        public string LuckyTime { get; set; }
        public string Appointment { get; set; }
        public Nullable<int> Company1 { get; set; }
        public Nullable<int> Company2 { get; set; }
        public Nullable<int> Contact1 { get; set; }
        public Nullable<int> Contact2 { get; set; }
        public short PayMethods { get; set; }
        public short woStatus { get; set; }
        public string timeRange { get; set; }
        public string timeRangeEnd { get; set; }
        public string timeAllowed { get; set; }
        public string timeAllowedEnd { get; set; }
        public Nullable<bool> ParkingAtSite { get; set; }
        public string ParkingLocation { get; set; }
        public Nullable<bool> ClientArrangeParking { get; set; }
        public string jobDescription { get; set; }
        public string graphicDwgPreparation { get; set; }
        public string structuralDwgPreparation { get; set; }
        public string SiteCheck { get; set; }
        public string clientApprovalSentDate { get; set; }
        public string clientApprovedDate { get; set; }
        public string landlordApprovalSendDate { get; set; }
        public string landlordApprovedDate { get; set; }
        public string engineeringStampSentDate { get; set; }
        public string engineeringStamped { get; set; }
        public string permit { get; set; }
        public string stakeout { get; set; }
        public string outsourcingInstaller { get; set; }
        public string Remarks { get; set; }
        public int Sales { get; set; }
        public Nullable<int> Sa1ID { get; set; }
        public Nullable<int> preWorkOrder { get; set; }
        public string switchPosition { get; set; }
        public Nullable<int> temp1 { get; set; }
        public string siteSupervisor { get; set; }
        public string ClientName { get; set; }
        public string coordinator { get; set; }
        public bool reDo { get; set; }
        public bool rush { get; set; }
        public bool revise { get; set; }
        public string rushReason { get; set; }
        public string redoReason { get; set; }
        public string revisedReason { get; set; }
        public string addNewItemReason { get; set; }
        public Nullable<bool> CurrentRev { get; set; }
        public Nullable<bool> NochargeApproved { get; set; }
        public Nullable<bool> Approved1 { get; set; }
        public Nullable<int> invID { get; set; }
        public Nullable<short> redoVer { get; set; }
        public Nullable<short> reviseVer { get; set; }
        public string NoChargeReason { get; set; }
        public bool ExactDate { get; set; }
        public string RedoOfWoNumbers { get; set; }
        public Nullable<byte> GenerateFrom { get; set; }
        public string PreviousServiceWO { get; set; }
        public bool ChecklistApplicable { get; set; }
        public int LongestLeadtime { get; set; }
        public bool SpecialProcedureApplicable { get; set; }
        public bool RushChargeApplied { get; set; }
        public double RushChargeAmount { get; set; }
        public Nullable<System.DateTime> SalesProposedDeadline { get; set; }
        public Nullable<System.DateTime> SalesProposedDeadlinePrevious { get; set; }
        public Nullable<System.DateTime> SalesProposedDeadlineLastUpdateWhen { get; set; }
        public int SalesProposedDeadlineLastUpdateWho { get; set; }
        public Nullable<System.DateTime> ProductionProposedDeadline { get; set; }
        public Nullable<System.DateTime> ProductionProposedDeadlinePrevious { get; set; }
        public Nullable<System.DateTime> ProductionProposedDeadlineLastUpdateWhen { get; set; }
        public int ProductionProposedDeadlineLastUpdateWho { get; set; }
        public Nullable<System.DateTime> FinalDeadLine { get; set; }
        public Nullable<System.DateTime> FinalDeadlinePrevious { get; set; }
        public Nullable<int> FinalDeadlineLastUpdateWho { get; set; }
        public Nullable<System.DateTime> FinalDeadlineLastUpdateWhen { get; set; }
        public Nullable<System.DateTime> RevisedDeadline { get; set; }
        public Nullable<System.DateTime> RevisedDeadlinePrevious { get; set; }
        public Nullable<int> RevisedDeadlineLastUpdateWho { get; set; }
        public Nullable<System.DateTime> RevisedDeadlineLastUpdateWhen { get; set; }
        public bool IsDisplayToPurchasingInfo { get; set; }
        public Nullable<double> EstimatedShippingCharge { get; set; }
        public string FedTaxIDNumber { get; set; }
        public double WorkorderAmount { get; set; }
        public Nullable<double> WorkorderAmountShopOnGoing { get; set; }
        public Nullable<double> WorkorderAmountShopOriginal { get; set; }
        public Nullable<double> WorkorderAmountInstallation { get; set; }
        public Nullable<double> WorkorderAmountSubcontract { get; set; }
    
        public virtual ICollection<Sales_JobMasterList_WO_Note> Sales_JobMasterList_WO_Note { get; set; }
        public virtual ICollection<WO_Item> WO_Item { get; set; }
        public virtual ICollection<WO_Shipping> WO_Shipping { get; set; }
        public virtual ICollection<WO_ShippingItem> WO_ShippingItem { get; set; }
        public virtual Sales_JobMasterList Sales_JobMasterList { get; set; }
        public virtual ICollection<FW_WORK_ORDER> FW_WORK_ORDER { get; set; }
        public virtual FW_Employees FW_Employees { get; set; }
    }
}
