//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_JobMaster_BiddingJob
    {
        public int BiddingID { get; set; }
        public int JobID { get; set; }
        public int BillToID { get; set; }
        public int InstallToID { get; set; }
        public int QuoteToID { get; set; }
        public int SubmitID { get; set; }
        public bool IsValid { get; set; }
        public string TempCompanyName { get; set; }
        public int BiddingSourceID { get; set; }
        public int BiddingTypeID { get; set; }
        public string ProductRequired { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> AeAssignedDate { get; set; }
        public Nullable<System.DateTime> BidDeadline { get; set; }
        public string TempProjectName { get; set; }
        public Nullable<System.DateTime> TempTargetDate { get; set; }
        public int TempAE { get; set; }
        public Nullable<double> TempAmount { get; set; }
        public string Winner { get; set; }
        public Nullable<double> WinnerAmount { get; set; }
        public string Remark { get; set; }
    
        public virtual Sales_JobMasterList Sales_JobMasterList { get; set; }
        public virtual TblBiddingJobType TblBiddingJobType { get; set; }
        public virtual TblBiddingJobSource TblBiddingJobSource { get; set; }
    }
}
