//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_JobMasterList_Customer
    {
        public int jcID { get; set; }
        public int jobID { get; set; }
        public int cID { get; set; }
        public int contactName { get; set; }
        public bool isBillTo { get; set; }
        public bool isQuoteTo { get; set; }
        public bool isInstallOrShipTo { get; set; }
    
        public virtual Sales_JobMasterList Sales_JobMasterList { get; set; }
    }
}
