//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_JobMasterList_Invoice
    {
        public Sales_JobMasterList_Invoice()
        {
            this.CommissionInforInvoices = new HashSet<CommissionInforInvoice>();
            this.CR_Commission = new HashSet<CR_Commission>();
            this.CR_Commission_InvoiceList = new HashSet<CR_Commission_InvoiceList>();
            this.Invoice_Item = new HashSet<Invoice_Item>();
            this.Sales_JobMaster_Invoice_CommissionOnHold = new HashSet<Sales_JobMaster_Invoice_CommissionOnHold>();
            this.Sales_JobMasterList_Invoice_Workorder = new HashSet<Sales_JobMasterList_Invoice_Workorder>();
        }
    
        public int invoiceID { get; set; }
        public int jobID { get; set; }
        public string invoiceNo { get; set; }
        public byte Revision { get; set; }
        public short invoiceType { get; set; }
        public Nullable<System.DateTime> invoiceDate { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<short> Term { get; set; }
        public string Workorders { get; set; }
        public string ContractNo { get; set; }
        public string ShipVia { get; set; }
        public Nullable<bool> Approved1 { get; set; }
        public Nullable<bool> Approved2 { get; set; }
        public Nullable<short> Operator { get; set; }
        public Nullable<System.DateTime> Datetimestamp { get; set; }
        public Nullable<bool> gst { get; set; }
        public Nullable<bool> pst { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Final { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Sales { get; set; }
        public Nullable<short> iStatus { get; set; }
        public string jobLocation { get; set; }
        public Nullable<byte> fromWhere { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public string po { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public int SA1 { get; set; }
        public string atDetails { get; set; }
        public string ActionTaken { get; set; }
        public short emptyRows3 { get; set; }
        public short emptyRows1 { get; set; }
        public short emptyRows2 { get; set; }
        public decimal pstAmount { get; set; }
        public Nullable<System.DateTime> contractDate { get; set; }
        public Nullable<decimal> CurrencyRate { get; set; }
        public decimal Discount { get; set; }
        public string Title { get; set; }
        public short printOption { get; set; }
        public bool isMultipleLegalName { get; set; }
        public string MultipleLegalNameText { get; set; }
        public short TaxOption { get; set; }
        public string NameSurfix { get; set; }
        public string WorkordersCopy { get; set; }
        public int AETM { get; set; }
        public int InternalReferral { get; set; }
        public int OriginalAccountOwner { get; set; }
        public bool IsAlert { get; set; }
        public string AlertReason { get; set; }
        public Nullable<double> CommissionAmountAdjustment { get; set; }
        public Nullable<double> CommissionCustomRate { get; set; }
        public bool CommissionIsWaived { get; set; }
        public string CommissionRemark { get; set; }
        public Nullable<double> CommissionAmountAdjustmentOP { get; set; }
    
        public virtual ICollection<CommissionInforInvoice> CommissionInforInvoices { get; set; }
        public virtual ICollection<CR_Commission> CR_Commission { get; set; }
        public virtual ICollection<CR_Commission_InvoiceList> CR_Commission_InvoiceList { get; set; }
        public virtual ICollection<Invoice_Item> Invoice_Item { get; set; }
        public virtual ICollection<Sales_JobMaster_Invoice_CommissionOnHold> Sales_JobMaster_Invoice_CommissionOnHold { get; set; }
        public virtual ICollection<Sales_JobMasterList_Invoice_Workorder> Sales_JobMasterList_Invoice_Workorder { get; set; }
        public virtual Sales_JobMasterList Sales_JobMasterList { get; set; }
    }
}
