//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_JobMasterList_QuoteRev
    {
        public Sales_JobMasterList_QuoteRev()
        {
            this.Quote_Item = new HashSet<Quote_Item>();
        }
    
        public int quoteRevID { get; set; }
        public int estRevID { get; set; }
        public int jobID { get; set; }
        public Nullable<byte> quoteRev { get; set; }
        public Nullable<short> quoteOption { get; set; }
        public Nullable<decimal> quoteAmount { get; set; }
        public Nullable<bool> quoteGST { get; set; }
        public Nullable<bool> quotePST { get; set; }
        public Nullable<short> termDeposit { get; set; }
        public Nullable<short> termBalance { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> followupDate { get; set; }
        public Nullable<bool> quoteLocked { get; set; }
        public Nullable<short> quoteStatus { get; set; }
        public Nullable<decimal> contractAmount { get; set; }
        public string contractNumber { get; set; }
        public Nullable<bool> isItemCopied { get; set; }
        public string reasonOfAddProduct { get; set; }
        public Nullable<short> printOption { get; set; }
        public string DiscountText { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<System.DateTime> isssueDate { get; set; }
        public byte emptyRow1 { get; set; }
        public byte emptyRow2 { get; set; }
        public byte emptyRow3 { get; set; }
        public decimal pstAmount { get; set; }
        public decimal CurrencyRate { get; set; }
        public Nullable<System.DateTime> contractDate { get; set; }
        public bool printJobTitle { get; set; }
        public bool isLost { get; set; }
        public int sa1ID { get; set; }
        public short TaxOption { get; set; }
        public short ReportFormat { get; set; }
        public string ContractFilename { get; set; }
    
        public virtual ICollection<Quote_Item> Quote_Item { get; set; }
        public virtual Sales_JobMasterList Sales_JobMasterList { get; set; }
    }
}
