//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_JobMasterList
    {
        public Sales_JobMasterList()
        {
            this.CR_OnGoingContract = new HashSet<CR_OnGoingContract>();
            this.CR_ProjectStage = new HashSet<CR_ProjectStage>();
            this.CR_ProjectWip = new HashSet<CR_ProjectWip>();
            this.CR_ProjectWipDetails = new HashSet<CR_ProjectWipDetails>();
            this.CR_WorkOnHandForAccounting = new HashSet<CR_WorkOnHandForAccounting>();
            this.Sales_Dispatching = new HashSet<Sales_Dispatching>();
            this.Sales_JobMasterList_Customer = new HashSet<Sales_JobMasterList_Customer>();
            this.Sales_JobMasterList_Invoice = new HashSet<Sales_JobMasterList_Invoice>();
            this.Sales_JobMasterList_QuoteRev = new HashSet<Sales_JobMasterList_QuoteRev>();
            this.Sales_JobMasterList_WO = new HashSet<Sales_JobMasterList_WO>();
            this.Sales_JobStatusTable = new HashSet<Sales_JobStatusTable>();
            this.Sales_SpecialMaterial = new HashSet<Sales_SpecialMaterial>();
            this.Sales_SpecialMaterialRequest = new HashSet<Sales_SpecialMaterialRequest>();
            this.Sales_Wip = new HashSet<Sales_Wip>();
            this.Sales_WipPublic = new HashSet<Sales_WipPublic>();
            this.Sales_JobMasterList_QuoteFollow = new HashSet<Sales_JobMasterList_QuoteFollow>();
            this.Sales_JobMaster_BiddingJob = new HashSet<Sales_JobMaster_BiddingJob>();
        }
    
        public int jobID { get; set; }
        public string jobNumber { get; set; }
        public Nullable<short> JobStatus { get; set; }
        public string jobTitle { get; set; }
        public Nullable<System.DateTime> OriginalTargetDate { get; set; }
        public Nullable<System.DateTime> targetDate { get; set; }
        public int sales { get; set; }
        public int sa1ID { get; set; }
        public Nullable<int> ObsoleteestimationRevID { get; set; }
        public Nullable<int> ObsoletequoteRevID { get; set; }
        public Nullable<System.DateTime> startTimeStamp { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Rush { get; set; }
        public Nullable<bool> StatusChanged { get; set; }
        public string timeLimit { get; set; }
        public bool isBidToProject { get; set; }
        public short subProject { get; set; }
        public short yearNumber { get; set; }
        public int Customer { get; set; }
        public int SalesType { get; set; }
        public bool isLost { get; set; }
        public string idCode { get; set; }
        public string locationCode { get; set; }
        public string ReasonOfNoContract { get; set; }
        public int MarketingTeam { get; set; }
        public int MarketingProduct { get; set; }
        public int MarketingAttribute { get; set; }
        public int InternalReferralEmployeeID { get; set; }
        public int OriginalAccountOwner { get; set; }
        public int AETM { get; set; }
        public bool IsPaidPremiu { get; set; }
        public Nullable<double> OverLimitRate { get; set; }
        public int ProductLine { get; set; }
        public int ProjectGiveBy { get; set; }
        public int PreviousProjectID { get; set; }
        public bool IsGivenByOldPartner { get; set; }
        public string ReasonOfNoWorkorder { get; set; }
        public Nullable<System.DateTime> FollowupDate1 { get; set; }
        public Nullable<System.DateTime> FollowupDate2 { get; set; }
        public int LeadID { get; set; }
        public int LastEstItemID { get; set; }
        public int LastQuoteItemID { get; set; }
        public int LastWorkorderItemID { get; set; }
        public int LastInvoiceItemID { get; set; }
        public double IssuedWorkorderAmount { get; set; }
        public bool IsAllProductionWorkorderIssued { get; set; }
        public double FinishedWorkorderAmount { get; set; }
        public bool IsAllProductionWorkorderFinished { get; set; }
        public bool IsOnHold { get; set; }
        public int AbnormalWorkorderIssueStatus { get; set; }
        public string AbnormalWorkorderIssueReason { get; set; }
        public bool IsFinished { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
        public bool IsOrderConfirmationSent { get; set; }
        public int OrderConfirmationPrinted { get; set; }
        public int OrderConfirmationSenderID { get; set; }
        public Nullable<System.DateTime> OrderConfirmationSentTime { get; set; }
        public string reasonOfLoss { get; set; }
        public string WipRemark { get; set; }
        public int CommissionGivenBy { get; set; }
        public Nullable<double> PreviousInvoiceAmount { get; set; }
        public Nullable<double> IssuedWorkorderAmountShop { get; set; }
        public Nullable<double> IssuedWorkorderAmountInstallation { get; set; }
        public Nullable<double> IssuedWorkorderAmountLocalInstaller { get; set; }
        public bool IsExcludedFromReceivable { get; set; }
    
        public virtual ICollection<CR_OnGoingContract> CR_OnGoingContract { get; set; }
        public virtual ICollection<CR_ProjectStage> CR_ProjectStage { get; set; }
        public virtual ICollection<CR_ProjectWip> CR_ProjectWip { get; set; }
        public virtual ICollection<CR_ProjectWipDetails> CR_ProjectWipDetails { get; set; }
        public virtual ICollection<CR_WorkOnHandForAccounting> CR_WorkOnHandForAccounting { get; set; }
        public virtual ICollection<Sales_Dispatching> Sales_Dispatching { get; set; }
        public virtual ICollection<Sales_JobMasterList_Customer> Sales_JobMasterList_Customer { get; set; }
        public virtual ICollection<Sales_JobMasterList_Invoice> Sales_JobMasterList_Invoice { get; set; }
        public virtual ICollection<Sales_JobMasterList_QuoteRev> Sales_JobMasterList_QuoteRev { get; set; }
        public virtual ICollection<Sales_JobMasterList_WO> Sales_JobMasterList_WO { get; set; }
        public virtual ICollection<Sales_JobStatusTable> Sales_JobStatusTable { get; set; }
        public virtual ICollection<Sales_SpecialMaterial> Sales_SpecialMaterial { get; set; }
        public virtual ICollection<Sales_SpecialMaterialRequest> Sales_SpecialMaterialRequest { get; set; }
        public virtual ICollection<Sales_Wip> Sales_Wip { get; set; }
        public virtual ICollection<Sales_WipPublic> Sales_WipPublic { get; set; }
        public virtual ICollection<Sales_JobMasterList_QuoteFollow> Sales_JobMasterList_QuoteFollow { get; set; }
        public virtual ICollection<Sales_JobMaster_BiddingJob> Sales_JobMaster_BiddingJob { get; set; }
        public virtual FW_Employees FW_Employees { get; set; }
    }
}
