//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_JobMasterList_Invoice_Workorder
    {
        public int ID { get; set; }
        public int InvoiceID { get; set; }
        public string WorkorderNumber { get; set; }
        public Nullable<int> woID { get; set; }
    
        public virtual Sales_JobMasterList_Invoice Sales_JobMasterList_Invoice { get; set; }
    }
}
