//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBiddingJobSource
    {
        public TblBiddingJobSource()
        {
            this.Sales_JobMaster_BiddingJob = new HashSet<Sales_JobMaster_BiddingJob>();
        }
    
        public int BiddingJobSourceID { get; set; }
        public string BiddingJobSourceName { get; set; }
    
        public virtual ICollection<Sales_JobMaster_BiddingJob> Sales_JobMaster_BiddingJob { get; set; }
    }
}
