//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class WO_Item
    {
        public int woItemID { get; set; }
        public int woID { get; set; }
        public long estItemID { get; set; }
        public string woDescription { get; set; }
        public Nullable<short> woPrintOrder { get; set; }
        public Nullable<short> scPurpose { get; set; }
        public string scFindSiteAt { get; set; }
        public Nullable<bool> scHydroInspectionRequired { get; set; }
        public string scPurposeOther { get; set; }
        public Nullable<short> qty { get; set; }
        public Nullable<short> qtyPC { get; set; }
        public string heightFromGround { get; set; }
        public int Requirement { get; set; }
        public string Position { get; set; }
        public string estItemNameText { get; set; }
        public Nullable<bool> scPurpose1 { get; set; }
        public Nullable<bool> scPurpose2 { get; set; }
        public Nullable<bool> scPurpose3 { get; set; }
        public Nullable<bool> scPurpose4 { get; set; }
        public Nullable<short> fromWhere { get; set; }
        public string qtyUnit { get; set; }
        public string qtyPcUnit { get; set; }
        public int NameDetailsID { get; set; }
        public double qiAmount { get; set; }
        public int LeadTime { get; set; }
        public string ReasonOfAlterLeadtime { get; set; }
        public string SerialID { get; set; }
        public bool BySubcontractor { get; set; }
        public bool IsHide { get; set; }
    
        public virtual FW_JOB_TYPE FW_JOB_TYPE { get; set; }
        public virtual Sales_JobMasterList_WO Sales_JobMasterList_WO { get; set; }
    }
}
