//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EmployeeDomain.Models
{
    public partial class CR_Timecard_Summary
    {
        public int SummaryID { get; set; }
        public int PrintingEmployeeID { get; set; }
        public string PayRollID { get; set; }
        public string eName { get; set; }
        public int WeekNumber { get; set; }
        public double WorkedHour { get; set; }
        public double RegularHour { get; set; }
        public double RegularOvertime { get; set; }
        public double HolidayHour { get; set; }
        public double HolidayOvertime { get; set; }
        public int eID { get; set; }
        public int ProcedureGroupID { get; set; }
    
        public virtual FW_Employees FW_Employees { get; set; }
    }
    
}
