//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EmployeeDomain.Models
{
    public partial class CR_TimeCard
    {
        public int tcID { get; set; }
        public int PrintingEmployeeID { get; set; }
        public int eID { get; set; }
        public System.DateTime CLOCK_IN { get; set; }
        public System.DateTime CLOCK_OUT { get; set; }
        public double Hours { get; set; }
        public string DepartmentName { get; set; }
        public string eName { get; set; }
        public long TRANSACTION_ID { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public string DEPARTMENT_ID { get; set; }
        public double HOURS_WORKED { get; set; }
        public double HOURS_BREAK { get; set; }
        public double HOURS_PREVIOUS { get; set; }
        public double HOURS_OVERALL { get; set; }
        public string SETUP_COMPLETED { get; set; }
        public string pID { get; set; }
        public int EarningCode { get; set; }
        public int SubstitudeID { get; set; }
        public int OvertimeID { get; set; }
        public int ShiftID { get; set; }
        public System.DateTime PayableClockIn { get; set; }
        public System.DateTime PayableClockOut { get; set; }
        public int WeekNumber { get; set; }
        public int PayrollPeriodID { get; set; }
        public int ProcedureGroupID { get; set; }
    
        public virtual PayrollPeriod PayrollPeriod { get; set; }
        public virtual FW_Employees FW_Employees { get; set; }
    }
    
}
