//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EmployeeDomain.Models
{
    public partial class FW_Employee_Substitude
    {
        public int SubstitudeID { get; set; }
        public int EmployeeID { get; set; }
        public int HolidayID { get; set; }
        public Nullable<System.DateTime> SubstitudeDate { get; set; }
        public int Status { get; set; }
    
        public virtual tblTimeCard_Holiday tblTimeCard_Holiday { get; set; }
        public virtual FW_Employees FW_Employees { get; set; }
    }
    
}
