//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EmployeeDomain.Models
{
    public partial class FW_Employee_Shift
    {
        public int rowID { get; set; }
        public int ShiftID { get; set; }
        public int EmployeeNumber { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public bool Active { get; set; }
    
        public virtual tblTimeCard_Shift tblTimeCard_Shift { get; set; }
        public virtual FW_Employees FW_Employees { get; set; }
    }
    
}
