//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EmployeeDomain.Models
{
    public partial class FW_Employee_WorkingHistory
    {
        public int eWorkingHistoryID { get; set; }
        public int EmployeeNumber { get; set; }
        public Nullable<System.DateTime> StartWorkingDate { get; set; }
        public Nullable<System.DateTime> EndWorkingDate { get; set; }
        public string Note { get; set; }
    
        public virtual FW_Employees FW_Employees { get; set; }
    }
    
}
