//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EmployeeDomain.Models
{
    public partial class FW_Employees
    {
        public FW_Employees()
        {
            this.CR_TimeCard = new HashSet<CR_TimeCard>();
            this.CR_Timecard_Substitude = new HashSet<CR_Timecard_Substitude>();
            this.CR_Timecard_Summary = new HashSet<CR_Timecard_Summary>();
            this.FW_Employee_Overtime = new HashSet<FW_Employee_Overtime>();
            this.FW_Employee_Shift = new HashSet<FW_Employee_Shift>();
            this.FW_Employee_Substitude = new HashSet<FW_Employee_Substitude>();
            this.FW_Employee_WorkingHistory = new HashSet<FW_Employee_WorkingHistory>();
            this.FwLabourTicketStationEmployees = new HashSet<FwLabourTicketStationEmployee>();
        }
    
        public int EmployeeNumber { get; set; }
        public string NickName { get; set; }
        public string Department { get; set; }
        public bool Active { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string DisplayName { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> SINCardNumber { get; set; }
        public string EmailAddress { get; set; }
        public string EmergencyContactPerson { get; set; }
        public string EmergencyContactNumber1 { get; set; }
        public string EmergencyContactNumber2 { get; set; }
        public string Position { get; set; }
        public Nullable<int> paytype { get; set; }
        public Nullable<int> payrate { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyCellphone { get; set; }
        public string Extension { get; set; }
        public string Performance { get; set; }
        public string History { get; set; }
        public string Training { get; set; }
        public string NumberInfor { get; set; }
        public string Password { get; set; }
        public string Roles { get; set; }
        public string UserName { get; set; }
        public string Sa1Name { get; set; }
        public string Sa2Name { get; set; }
        public string SalesName { get; set; }
        public string Notes { get; set; }
        public int PayrollNumber { get; set; }
        public string DepartmentID { get; set; }
        public bool ncrEnable { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<bool> response { get; set; }
        public byte[] signature { get; set; }
        public int dID { get; set; }
        public int Team { get; set; }
        public bool isLeadHand { get; set; }
        public bool isAE { get; set; }
        public int Role { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> StartWorkingDate { get; set; }
        public Nullable<System.DateTime> EndWorkingDate1 { get; set; }
        public Nullable<System.DateTime> ReturnToWorkDate { get; set; }
        public Nullable<System.DateTime> EndWorkingDate2 { get; set; }
        public short SelectType { get; set; }
        public string IsProbation { get; set; }
        public bool IsInProbation { get; set; }
        public int ProbationPeriod { get; set; }
        public bool ShowOnInputHour { get; set; }
        public bool IsFake { get; set; }
        public bool IsShowOnPerformanceReport { get; set; }
        public bool ShowOnCrmPage1 { get; set; }
        public bool ShowOnCommissionPage1 { get; set; }
        public bool ShowOnCommissionPage2 { get; set; }
        public bool CrmLeadOwner { get; set; }
        public bool CrmLeadAE { get; set; }
        public bool CrmLeadSelectAeEnable { get; set; }
        public bool IsAdminTaskSelected { get; set; }
        public bool IsShowOnSubdepartmentSchedule { get; set; }
        public bool IsMtoAwared { get; set; }
        public int ProcedureGroupID { get; set; }
        public int EntityID { get; set; }
        public bool IsSubcontract { get; set; }
    
        public virtual ICollection<CR_TimeCard> CR_TimeCard { get; set; }
        public virtual ICollection<CR_Timecard_Substitude> CR_Timecard_Substitude { get; set; }
        public virtual ICollection<CR_Timecard_Summary> CR_Timecard_Summary { get; set; }
        public virtual FW_Department1 FW_Department1 { get; set; }
        public virtual ICollection<FW_Employee_Overtime> FW_Employee_Overtime { get; set; }
        public virtual ICollection<FW_Employee_Shift> FW_Employee_Shift { get; set; }
        public virtual ICollection<FW_Employee_Substitude> FW_Employee_Substitude { get; set; }
        public virtual ICollection<FW_Employee_WorkingHistory> FW_Employee_WorkingHistory { get; set; }
        public virtual FW_EmployeesTeam FW_EmployeesTeam { get; set; }
        public virtual ICollection<FwLabourTicketStationEmployee> FwLabourTicketStationEmployees { get; set; }
    }
    
}
