//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EmployeeDomain.Models
{
    public partial class FwLabourTicketStationEmployee
    {
        public int RowID { get; set; }
        public int StationID { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual FW_Employees FW_Employees { get; set; }
    }
    
}
