//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_CostItem
    {
        public long CostItemID { get; set; }
        public int ProjectID { get; set; }
        public int EstRevID { get; set; }
        public long EstItemID { get; set; }
        public int WorkorderID { get; set; }
        public long WorkorderItemID { get; set; }
        public int PrintingEmployeeID { get; set; }
        public int TypeOrderNumber { get; set; }
        public int TypeID { get; set; }
        public string TypeName { get; set; }
        public int ItemOrderNumber { get; set; }
        public string CosItemName { get; set; }
        public string Unit { get; set; }
        public double UnitPrice { get; set; }
        public double Qty { get; set; }
        public double SubTotal { get; set; }
    
        public virtual EST_Cost_Type EST_Cost_Type { get; set; }
        public virtual Sales_JobMasterList_EstRev Sales_JobMasterList_EstRev { get; set; }
    }
}
