//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_EstimationRequisitionTitle
    {
        public int ID { get; set; }
        public int EstRevID { get; set; }
        public int JobID { get; set; }
        public int SubProjectNumber { get; set; }
        public int PrintingEmployeeID { get; set; }
        public string JobNumber { get; set; }
        public string JobTitle { get; set; }
        public bool IsBidToProject { get; set; }
        public string TargetDate { get; set; }
        public string QuoteToCompanyName { get; set; }
        public string JobLocation { get; set; }
        public int IndustryCodeID { get; set; }
        public int Rev { get; set; }
        public bool IsLocked { get; set; }
        public bool IsRush { get; set; }
        public string SalesName { get; set; }
        public string SubmittedTime { get; set; }
        public string Estimator { get; set; }
        public string FinishedTime { get; set; }
        public string Remark { get; set; }
        public int DrawingPurpose { get; set; }
        public string MallID { get; set; }
    
        public virtual Sales_JobMasterList_EstRev Sales_JobMasterList_EstRev { get; set; }
    }
}
