//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_Cost_Bid_ParentItem
    {
        public int ParentItemRowID { get; set; }
        public int ParentTypeID { get; set; }
        public int EstRevID { get; set; }
        public double OrderNumber { get; set; }
        public Nullable<double> Subtoal { get; set; }
        public string Note { get; set; }
        public int ChildrenRowCount { get; set; }
    
        public virtual EST_Cost_Bid_Type_Parent EST_Cost_Bid_Type_Parent { get; set; }
        public virtual Sales_JobMasterList_EstRev Sales_JobMasterList_EstRev { get; set; }
    }
}
