//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_Cost_Configuration
    {
        public long ConfigID { get; set; }
        public int EstRevID { get; set; }
        public double MaterialMarkupPercentage { get; set; }
        public double DiscountRate { get; set; }
        public double LabourRateShop { get; set; }
        public double LabourRateInstallation { get; set; }
        public double OverheadRate { get; set; }
        public double TargetProfitRate { get; set; }
        public double MarkupShopMaterial { get; set; }
        public double MarkupInstallationMaterial { get; set; }
        public double MarkupStandardItem { get; set; }
        public double LabourRateLocalInstaller { get; set; }
        public double MaterialWastageRate { get; set; }
    
        public virtual Sales_JobMasterList_EstRev Sales_JobMasterList_EstRev { get; set; }
    }
}
