//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_Cost_Bid_Type_Children
    {
        public EST_Cost_Bid_Type_Children()
        {
            this.EST_Cost_Bid_Item = new HashSet<EST_Cost_Bid_Item>();
        }
    
        public int ChildrenTypeID { get; set; }
        public int ParentTypeID { get; set; }
        public int ChildrenOrderNumber { get; set; }
        public string ChildrenTypeName { get; set; }
        public bool IsSyncNeeded { get; set; }
        public bool IsTotalRow { get; set; }
        public bool IsDefault { get; set; }
        public int SummaryGroupID { get; set; }
        public int DistributionToItemGroupID { get; set; }
    
        public virtual ICollection<EST_Cost_Bid_Item> EST_Cost_Bid_Item { get; set; }
        public virtual EST_Cost_Bid_Type_Parent EST_Cost_Bid_Type_Parent { get; set; }
    }
}
