//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_Cost_Db_LabourHourProcedure
    {
        public int DbItemID { get; set; }
        public int EstCostTypeID { get; set; }
        public int PositionID { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public bool Active { get; set; }
        public Nullable<int> StatusID { get; set; }
        public int GroupID { get; set; }
    
        public virtual EST_Cost_Db_LabourHourPosition EST_Cost_Db_LabourHourPosition { get; set; }
        public virtual EST_Cost_Type EST_Cost_Type { get; set; }
        public virtual EST_Cost_Db_LabourHourGroup EST_Cost_Db_LabourHourGroup { get; set; }
    }
}
