//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_Cost_Type
    {
        public EST_Cost_Type()
        {
            this.CR_CostItem = new HashSet<CR_CostItem>();
            this.EST_Cost_Db_Other = new HashSet<EST_Cost_Db_Other>();
            this.EST_Cost_Template_Detail = new HashSet<EST_Cost_Template_Detail>();
            this.JobCostingOutsourcingTransactions = new HashSet<JobCostingOutsourcingTransaction>();
            this.EST_Cost_Db_LabourHourProcedure = new HashSet<EST_Cost_Db_LabourHourProcedure>();
            this.JobCostingTransactions = new HashSet<JobCostingTransaction>();
            this.EST_Cost = new HashSet<EST_Cost>();
        }
    
        public int TypeID { get; set; }
        public int CategoryID { get; set; }
        public int OrderNumber { get; set; }
        public string Name { get; set; }
        public double SubTotal { get; set; }
        public bool Active { get; set; }
        public bool IsOutsourcing { get; set; }
        public bool IsMarkupNeeded { get; set; }
        public int TemplateDbTypeID { get; set; }
    
        public virtual ICollection<CR_CostItem> CR_CostItem { get; set; }
        public virtual ICollection<EST_Cost_Db_Other> EST_Cost_Db_Other { get; set; }
        public virtual ICollection<EST_Cost_Template_Detail> EST_Cost_Template_Detail { get; set; }
        public virtual EST_Cost_Type_Category EST_Cost_Type_Category { get; set; }
        public virtual ICollection<JobCostingOutsourcingTransaction> JobCostingOutsourcingTransactions { get; set; }
        public virtual ICollection<EST_Cost_Db_LabourHourProcedure> EST_Cost_Db_LabourHourProcedure { get; set; }
        public virtual ICollection<JobCostingTransaction> JobCostingTransactions { get; set; }
        public virtual ICollection<EST_Cost> EST_Cost { get; set; }
    }
}
