//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_Item_Status
    {
        public EST_Item_Status()
        {
            this.Sales_Dispatching_DrawingRequisition_EstimationItem = new HashSet<Sales_Dispatching_DrawingRequisition_EstimationItem>();
            this.EST_Item = new HashSet<EST_Item>();
        }
    
        public int StatusID { get; set; }
        public string Name { get; set; }
        public Nullable<short> DirectionID { get; set; }
    
        public virtual ICollection<Sales_Dispatching_DrawingRequisition_EstimationItem> Sales_Dispatching_DrawingRequisition_EstimationItem { get; set; }
        public virtual ICollection<EST_Item> EST_Item { get; set; }
    }
}
