//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_Cost_Bid_Type_Summary
    {
        public EST_Cost_Bid_Type_Summary()
        {
            this.EST_Cost_Bid_Summary = new HashSet<EST_Cost_Bid_Summary>();
            this.CR_EstCostBidSummary = new HashSet<CR_EstCostBidSummary>();
        }
    
        public int SummaryTypeID { get; set; }
        public int PaOrderNumber { get; set; }
        public int PbOrderNumber { get; set; }
        public string SummaryTypeName { get; set; }
        public int PbCalculateOrder { get; set; }
        public int CategoryID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<EST_Cost_Bid_Summary> EST_Cost_Bid_Summary { get; set; }
        public virtual ICollection<CR_EstCostBidSummary> CR_EstCostBidSummary { get; set; }
    }
}
