//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_Service
    {
        public int qsID { get; set; }
        public Nullable<int> EstRevID { get; set; }
        public Nullable<short> qsPrintOrder { get; set; }
        public Nullable<short> qsServiceID { get; set; }
        public string qsTitle { get; set; }
        public string qsDescription { get; set; }
        public string qsAmount { get; set; }
        public Nullable<int> qsQty { get; set; }
        public Nullable<float> qsUnitPrice { get; set; }
        public string recordType { get; set; }
        public string qsAmountText { get; set; }
    
        public virtual Sales_JobMasterList_EstRev Sales_JobMasterList_EstRev { get; set; }
    }
}
