//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_Cost_Template_Detail
    {
        public int SubTemplateID { get; set; }
        public int TemplateID { get; set; }
        public int TypeID { get; set; }
        public int OrderNumber { get; set; }
        public int OptionGroupID { get; set; }
        public int DbItemID { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public double UnitPrice { get; set; }
        public double Qty { get; set; }
        public bool Active { get; set; }
    
        public virtual EST_Item_Specification_Template_OptionGroup EST_Item_Specification_Template_OptionGroup { get; set; }
        public virtual EST_Cost_Type EST_Cost_Type { get; set; }
        public virtual EST_Cost_Template EST_Cost_Template { get; set; }
    }
}
