//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_Item_Specification_Template_Option
    {
        public int OptionID { get; set; }
        public int OptionGroupID { get; set; }
        public string OptionName { get; set; }
        public bool Active { get; set; }
    
        public virtual EST_Item_Specification_Template_OptionGroup EST_Item_Specification_Template_OptionGroup { get; set; }
    }
}
