//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_Item_Specification_Template_OptionGroup
    {
        public EST_Item_Specification_Template_OptionGroup()
        {
            this.EST_Item_Specification = new HashSet<EST_Item_Specification>();
            this.EST_Item_Specification_Template_Option = new HashSet<EST_Item_Specification_Template_Option>();
            this.EST_Item_Specification_Template = new HashSet<EST_Item_Specification_Template>();
            this.EST_Cost_Template_Detail = new HashSet<EST_Cost_Template_Detail>();
        }
    
        public int OptionGroupID { get; set; }
        public string OptionGroupName { get; set; }
        public bool Active { get; set; }
        public string SysOptionGroupName { get; set; }
    
        public virtual ICollection<EST_Item_Specification> EST_Item_Specification { get; set; }
        public virtual ICollection<EST_Item_Specification_Template_Option> EST_Item_Specification_Template_Option { get; set; }
        public virtual ICollection<EST_Item_Specification_Template> EST_Item_Specification_Template { get; set; }
        public virtual ICollection<EST_Cost_Template_Detail> EST_Cost_Template_Detail { get; set; }
    }
}
