//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_Cost_Db_LabourHourPosition
    {
        public EST_Cost_Db_LabourHourPosition()
        {
            this.EST_Cost_Db_LabourHourProcedure = new HashSet<EST_Cost_Db_LabourHourProcedure>();
        }
    
        public int PositionID { get; set; }
        public string PositionName { get; set; }
        public double RateA { get; set; }
        public double RateB { get; set; }
        public int Status { get; set; }
        public System.DateTime EffectiveDate { get; set; }
    
        public virtual ICollection<EST_Cost_Db_LabourHourProcedure> EST_Cost_Db_LabourHourProcedure { get; set; }
    }
}
