//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FW_JOB_TYPE
    {
        public FW_JOB_TYPE()
        {
            this.EST_Item = new HashSet<EST_Item>();
        }
    
        public int TYPE_ID { get; set; }
        public string JOB_TYPE { get; set; }
        public short QUOTE_SUPPLY_TYPE { get; set; }
        public bool wSelect { get; set; }
        public bool iSelect { get; set; }
        public bool sSelect { get; set; }
    
        public virtual ICollection<EST_Item> EST_Item { get; set; }
    }
}
