//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCostingMaterialTemplate
    {
        public JobCostingMaterialTemplate()
        {
            this.JobCostingMaterialTemplateDetails = new HashSet<JobCostingMaterialTemplateDetail>();
        }
    
        public int TemplateID { get; set; }
        public int ProductID { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public string Description { get; set; }
        public int LastUpdateBy { get; set; }
        public System.DateTime LastUpdatedAt { get; set; }
        public int DepartmentID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<JobCostingMaterialTemplateDetail> JobCostingMaterialTemplateDetails { get; set; }
    }
}
