//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCostingMaterialTemplateDetail
    {
        public int SubTemplateID { get; set; }
        public int TemplateID { get; set; }
        public int OrderNumber { get; set; }
        public int MaterialID { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public double UnitPrice { get; set; }
        public double Qty { get; set; }
    
        public virtual JobCostingMaterialTemplate JobCostingMaterialTemplate { get; set; }
        public virtual Material Material { get; set; }
    }
}
