//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.JobCostingMaterialTemplateDetails = new HashSet<JobCostingMaterialTemplateDetail>();
            this.MaterialPrices = new HashSet<MaterialPrice>();
            this.JobCostingTransactions = new HashSet<JobCostingTransaction>();
        }
    
        public int MaterialID { get; set; }
        public int CategoryID0 { get; set; }
        public int CategoryID1 { get; set; }
        public int CategoryID2 { get; set; }
        public int CategoryID3 { get; set; }
        public int CategoryID4 { get; set; }
        public string MaterialCode { get; set; }
        public string Remark { get; set; }
        public short Status { get; set; }
        public int PriceID { get; set; }
        public int UnitID { get; set; }
        public double Price { get; set; }
        public bool IsVirtual { get; set; }
        public int SyncLevel { get; set; }
        public int SyncMethod { get; set; }
        public double SynchronizedPrice { get; set; }
        public int ShortageWarningLevel { get; set; }
        public int TypeID { get; set; }
        public string SupplierName { get; set; }
        public string CombinedName { get; set; }
    
        public virtual ICollection<JobCostingMaterialTemplateDetail> JobCostingMaterialTemplateDetails { get; set; }
        public virtual MaterialCategory0 MaterialCategory0 { get; set; }
        public virtual MaterialCategory1 MaterialCategory1 { get; set; }
        public virtual MaterialCategory2 MaterialCategory2 { get; set; }
        public virtual MaterialCategory3 MaterialCategory3 { get; set; }
        public virtual MaterialCategory4 MaterialCategory4 { get; set; }
        public virtual MaterialPriceUnit MaterialPriceUnit { get; set; }
        public virtual ICollection<MaterialPrice> MaterialPrices { get; set; }
        public virtual ICollection<JobCostingTransaction> JobCostingTransactions { get; set; }
    }
}
