//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialPriceUnit
    {
        public MaterialPriceUnit()
        {
            this.Materials = new HashSet<Material>();
            this.MaterialPrices = new HashSet<MaterialPrice>();
        }
    
        public int UnitID { get; set; }
        public string UnitName { get; set; }
    
        public virtual ICollection<Material> Materials { get; set; }
        public virtual ICollection<MaterialPrice> MaterialPrices { get; set; }
    }
}
