//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialCategory2
    {
        public MaterialCategory2()
        {
            this.MaterialCategory3 = new HashSet<MaterialCategory3>();
            this.Materials = new HashSet<Material>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public int ParentID { get; set; }
        public short Status { get; set; }
    
        public virtual MaterialCategory1 MaterialCategory1 { get; set; }
        public virtual ICollection<MaterialCategory3> MaterialCategory3 { get; set; }
        public virtual ICollection<Material> Materials { get; set; }
    }
}
