//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterSpecification
    {
        public int EmployeeID { get; set; }
        public int ProjectID { get; set; }
        public int EstRevID { get; set; }
        public bool IsAuthorized { get; set; }
        public bool IsResponseOwner { get; set; }
        public bool IsRequestOwner { get; set; }
        public bool IsLocked { get; set; }
        public bool IsSpecificationTemplateEditEnabled { get; set; }
        public bool IsCostTemplateEditEnabled { get; set; }
    
        public virtual Sales_JobMasterList_EstRev Sales_JobMasterList_EstRev { get; set; }
    }
}
