//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSize
    {
        public int SizeID { get; set; }
        public int CategoryID { get; set; }
        public int ProductID { get; set; }
        public string Contents { get; set; }
        public bool Active { get; set; }
        public int SizeTotalRows { get; set; }
        public bool IsWidthEnabled { get; set; }
        public bool IsHeightEnabled { get; set; }
        public bool IsThicknessEnabled { get; set; }
        public bool IsPcEnabled { get; set; }
        public bool IsWidthMandatory { get; set; }
        public bool IsHeightMandatory { get; set; }
        public bool IsThicknessMandatory { get; set; }
        public bool IsPcEnabledMandatory { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
