//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFeatureGroup
    {
        public ProductFeatureGroup()
        {
            this.Products = new HashSet<Product>();
            this.ProductFeatures = new HashSet<ProductFeature>();
        }
    
        public int OptionGroupID { get; set; }
        public string OptionName { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<ProductFeature> ProductFeatures { get; set; }
    }
}
