//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.JobCostingMaterialTemplates = new HashSet<JobCostingMaterialTemplate>();
            this.EST_Item_Specification_Template = new HashSet<EST_Item_Specification_Template>();
            this.EST_Cost_Template = new HashSet<EST_Cost_Template>();
            this.EST_Item = new HashSet<EST_Item>();
        }
    
        public int ProductID { get; set; }
        public int CategoryID { get; set; }
        public string ProductName { get; set; }
        public int OptionID1 { get; set; }
        public int OptionID2 { get; set; }
        public int OptionID3 { get; set; }
        public bool Active { get; set; }
        public int SupplyAndInstall { get; set; }
        public int SupplyOnly { get; set; }
        public decimal BasePrice { get; set; }
    
        public virtual ICollection<JobCostingMaterialTemplate> JobCostingMaterialTemplates { get; set; }
        public virtual ProductFeatureGroup ProductFeatureGroup { get; set; }
        public virtual ICollection<EST_Item_Specification_Template> EST_Item_Specification_Template { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ICollection<EST_Cost_Template> EST_Cost_Template { get; set; }
        public virtual ICollection<EST_Item> EST_Item { get; set; }
    }
}
