//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequiredItemPosition
    {
        public RequiredItemPosition()
        {
            this.EST_Item = new HashSet<EST_Item>();
        }
    
        public int PositionID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<EST_Item> EST_Item { get; set; }
    }
}
