//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_JobMasterList_EstRev
    {
        public Sales_JobMasterList_EstRev()
        {
            this.CR_Cost_Summary = new HashSet<CR_Cost_Summary>();
            this.CR_CostItem = new HashSet<CR_CostItem>();
            this.EST_Cost_Bid_Item = new HashSet<EST_Cost_Bid_Item>();
            this.EST_Drawing = new HashSet<EST_Drawing>();
            this.EST_Service = new HashSet<EST_Service>();
            this.ParameterSpecifications = new HashSet<ParameterSpecification>();
            this.Sales_Dispatching = new HashSet<Sales_Dispatching>();
            this.Sales_Dispatching_DrawingRequisition_Estimation = new HashSet<Sales_Dispatching_DrawingRequisition_Estimation>();
            this.EST_Cost_Bid_Note = new HashSet<EST_Cost_Bid_Note>();
            this.EST_Cost_Configuration = new HashSet<EST_Cost_Configuration>();
            this.EST_Cost_Bid_ParentItem = new HashSet<EST_Cost_Bid_ParentItem>();
            this.EST_Cost_Bid_Summary = new HashSet<EST_Cost_Bid_Summary>();
            this.CR_EstimationRequisitionTitle = new HashSet<CR_EstimationRequisitionTitle>();
            this.CR_EstCostBidSummary = new HashSet<CR_EstCostBidSummary>();
            this.EST_Item = new HashSet<EST_Item>();
        }
    
        public int EstRevID { get; set; }
        public int JobID { get; set; }
        public byte erRev { get; set; }
        public bool erLocked { get; set; }
        public Nullable<decimal> erAmount { get; set; }
        public string noEstimationReason { get; set; }
        public int sa1ID { get; set; }
        public string Remark { get; set; }
        public long TaskID { get; set; }
        public Nullable<int> BidSignQty { get; set; }
        public string BidNote { get; set; }
        public Nullable<double> BidCashAllowance { get; set; }
        public Nullable<double> BidTaxRate { get; set; }
        public Nullable<double> BidTaxAmountA { get; set; }
        public Nullable<double> BidTaxAmountB { get; set; }
        public Nullable<double> PriceA { get; set; }
        public Nullable<double> PriceB { get; set; }
        public Nullable<double> SubtotalA { get; set; }
        public Nullable<double> SubtotalB { get; set; }
        public Nullable<double> QtySum { get; set; }
    
        public virtual ICollection<CR_Cost_Summary> CR_Cost_Summary { get; set; }
        public virtual ICollection<CR_CostItem> CR_CostItem { get; set; }
        public virtual ICollection<EST_Cost_Bid_Item> EST_Cost_Bid_Item { get; set; }
        public virtual ICollection<EST_Drawing> EST_Drawing { get; set; }
        public virtual ICollection<EST_Service> EST_Service { get; set; }
        public virtual ICollection<ParameterSpecification> ParameterSpecifications { get; set; }
        public virtual ICollection<Sales_Dispatching> Sales_Dispatching { get; set; }
        public virtual ICollection<Sales_Dispatching_DrawingRequisition_Estimation> Sales_Dispatching_DrawingRequisition_Estimation { get; set; }
        public virtual ICollection<EST_Cost_Bid_Note> EST_Cost_Bid_Note { get; set; }
        public virtual ICollection<EST_Cost_Configuration> EST_Cost_Configuration { get; set; }
        public virtual ICollection<EST_Cost_Bid_ParentItem> EST_Cost_Bid_ParentItem { get; set; }
        public virtual ICollection<EST_Cost_Bid_Summary> EST_Cost_Bid_Summary { get; set; }
        public virtual ICollection<CR_EstimationRequisitionTitle> CR_EstimationRequisitionTitle { get; set; }
        public virtual ICollection<CR_EstCostBidSummary> CR_EstCostBidSummary { get; set; }
        public virtual ICollection<EST_Item> EST_Item { get; set; }
    }
}
