//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Dispatching_DrawingReq_Purpose
    {
        public Sales_Dispatching_DrawingReq_Purpose()
        {
            this.Sales_Dispatching_DrawingRequisition_Estimation = new HashSet<Sales_Dispatching_DrawingRequisition_Estimation>();
        }
    
        public int RowID { get; set; }
        public short drawingPurposeID { get; set; }
        public string dpName { get; set; }
        public string step { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<Sales_Dispatching_DrawingRequisition_Estimation> Sales_Dispatching_DrawingRequisition_Estimation { get; set; }
    }
}
