//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Dispatching_DrawingRequisition_Estimation
    {
        public Sales_Dispatching_DrawingRequisition_Estimation()
        {
            this.Sales_Dispatching_DrawingRequisition_EstimationItem = new HashSet<Sales_Dispatching_DrawingRequisition_EstimationItem>();
        }
    
        public int RequisitionID { get; set; }
        public string DrawingType { get; set; }
        public int ProjectID { get; set; }
        public int EstRevID { get; set; }
        public int MallID { get; set; }
        public long SubmitID { get; set; }
        public int Version { get; set; }
        public int InstalltoCustomerID { get; set; }
        public int BillToCustomerID { get; set; }
        public int DrawingPurpose { get; set; }
        public int IsQuotationAvailable { get; set; }
        public int IsGCorDesignerDrawingAvailable { get; set; }
        public int IsSiteCheckPhotoAvailable { get; set; }
        public int IsSiteCheckReportAvailable { get; set; }
        public int IsLandordOrMallCriteriaAvailable { get; set; }
        public int IsElectronicFillFromClientAvailable { get; set; }
        public string Remark { get; set; }
        public bool IsValid { get; set; }
    
        public virtual Sales_Dispatching_DrawingReq_Purpose Sales_Dispatching_DrawingReq_Purpose { get; set; }
        public virtual ICollection<Sales_Dispatching_DrawingRequisition_EstimationItem> Sales_Dispatching_DrawingRequisition_EstimationItem { get; set; }
        public virtual Sales_JobMasterList_EstRev Sales_JobMasterList_EstRev { get; set; }
    }
}
