//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpecificationDbEntities : DbContext
    {
        public SpecificationDbEntities()
            : base("name=SpecificationDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EST_Cost_Type_Category> EST_Cost_Type_Category { get; set; }
        public virtual DbSet<EST_Drawing> EST_Drawing { get; set; }
        public virtual DbSet<EST_Item_Drawing> EST_Item_Drawing { get; set; }
        public virtual DbSet<EST_Item_Specification> EST_Item_Specification { get; set; }
        public virtual DbSet<EST_Item_Specification_Template_Option> EST_Item_Specification_Template_Option { get; set; }
        public virtual DbSet<EST_Item_Specification_Template_OptionGroup> EST_Item_Specification_Template_OptionGroup { get; set; }
        public virtual DbSet<EST_Item_Status> EST_Item_Status { get; set; }
        public virtual DbSet<EST_Item_TablePurpose> EST_Item_TablePurpose { get; set; }
        public virtual DbSet<EST_Service> EST_Service { get; set; }
        public virtual DbSet<FW_JOB_TYPE> FW_JOB_TYPE { get; set; }
        public virtual DbSet<JobCostingMaterialTemplate> JobCostingMaterialTemplates { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductFeature> ProductFeatures { get; set; }
        public virtual DbSet<ProductFeatureGroup> ProductFeatureGroups { get; set; }
        public virtual DbSet<RequiredItemPosition> RequiredItemPositions { get; set; }
        public virtual DbSet<CR_EstimationRequisitionItem> CR_EstimationRequisitionItem { get; set; }
        public virtual DbSet<Sales_Dispatching_DrawingReq_Purpose> Sales_Dispatching_DrawingReq_Purpose { get; set; }
        public virtual DbSet<EST_Item_Specification_Template> EST_Item_Specification_Template { get; set; }
        public virtual DbSet<Sales_Dispatching> Sales_Dispatching { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<ProductSize> ProductSizes { get; set; }
        public virtual DbSet<EST_Item_Specification_Size> EST_Item_Specification_Size { get; set; }
        public virtual DbSet<ParameterSpecification> ParameterSpecifications { get; set; }
        public virtual DbSet<Sales_Dispatching_DrawingRequisition_Estimation> Sales_Dispatching_DrawingRequisition_Estimation { get; set; }
        public virtual DbSet<JobCostingMaterialTemplateDetail> JobCostingMaterialTemplateDetails { get; set; }
        public virtual DbSet<MaterialPrice> MaterialPrices { get; set; }
        public virtual DbSet<EST_Cost_Db_Other> EST_Cost_Db_Other { get; set; }
        public virtual DbSet<CR_Cost_Summary> CR_Cost_Summary { get; set; }
        public virtual DbSet<EST_Cost_Template_Detail> EST_Cost_Template_Detail { get; set; }
        public virtual DbSet<CR_CostItem> CR_CostItem { get; set; }
        public virtual DbSet<EST_Cost_Type> EST_Cost_Type { get; set; }
        public virtual DbSet<Sales_Dispatching_DrawingRequisition_EstimationItem> Sales_Dispatching_DrawingRequisition_EstimationItem { get; set; }
        public virtual DbSet<MaterialCategory0> MaterialCategory0 { get; set; }
        public virtual DbSet<MaterialCategory1> MaterialCategory1 { get; set; }
        public virtual DbSet<MaterialCategory2> MaterialCategory2 { get; set; }
        public virtual DbSet<MaterialCategory3> MaterialCategory3 { get; set; }
        public virtual DbSet<MaterialCategory4> MaterialCategory4 { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<MaterialPriceUnit> MaterialPriceUnits { get; set; }
        public virtual DbSet<JobCostingOutsourcingTransaction> JobCostingOutsourcingTransactions { get; set; }
        public virtual DbSet<Sales_JobMasterList_WO> Sales_JobMasterList_WO { get; set; }
        public virtual DbSet<EST_Cost_Template> EST_Cost_Template { get; set; }
        public virtual DbSet<EST_Cost_Bid_Type_Parent> EST_Cost_Bid_Type_Parent { get; set; }
        public virtual DbSet<EST_Cost_Bid_Item> EST_Cost_Bid_Item { get; set; }
        public virtual DbSet<EST_Cost_Bid_Type_Children> EST_Cost_Bid_Type_Children { get; set; }
        public virtual DbSet<Sales_JobMasterList_EstRev> Sales_JobMasterList_EstRev { get; set; }
        public virtual DbSet<EST_Cost_Bid_Note> EST_Cost_Bid_Note { get; set; }
        public virtual DbSet<EST_Cost_Bid_Note_Base> EST_Cost_Bid_Note_Base { get; set; }
        public virtual DbSet<EST_Cost_Bid_Type_Summary> EST_Cost_Bid_Type_Summary { get; set; }
        public virtual DbSet<EST_Cost_Configuration> EST_Cost_Configuration { get; set; }
        public virtual DbSet<EST_Cost_Bid_ParentItem> EST_Cost_Bid_ParentItem { get; set; }
        public virtual DbSet<EST_Cost_Bid_Summary> EST_Cost_Bid_Summary { get; set; }
        public virtual DbSet<CR_EstimationRequisitionTitle> CR_EstimationRequisitionTitle { get; set; }
        public virtual DbSet<CR_EstCostBidSummary> CR_EstCostBidSummary { get; set; }
        public virtual DbSet<EST_Cost_Db_LabourHourPosition> EST_Cost_Db_LabourHourPosition { get; set; }
        public virtual DbSet<EST_Cost_Db_LabourHourProcedure> EST_Cost_Db_LabourHourProcedure { get; set; }
        public virtual DbSet<EST_Item> EST_Item { get; set; }
        public virtual DbSet<JobCostingTransaction> JobCostingTransactions { get; set; }
        public virtual DbSet<EST_Cost_Db_LabourHourGroup> EST_Cost_Db_LabourHourGroup { get; set; }
        public virtual DbSet<tblWorkshopProductionProcessStep> tblWorkshopProductionProcessSteps { get; set; }
        public virtual DbSet<EST_Cost> EST_Cost { get; set; }
    }
}
