//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkshopProductionProcessStep
    {
        public int ID { get; set; }
        public int DepartmentID { get; set; }
        public string Contents { get; set; }
        public bool Active { get; set; }
        public int ProcedureGroupID { get; set; }
    
        public virtual EST_Cost_Db_LabourHourGroup EST_Cost_Db_LabourHourGroup { get; set; }
    }
}
