#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportDomain.Parameter
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sqllhdb")]
	public partial class ExportParameterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertExportParameter(ExportParameter instance);
    partial void UpdateExportParameter(ExportParameter instance);
    partial void DeleteExportParameter(ExportParameter instance);
    #endregion
		
		public ExportParameterDataContext() : 
				base(global::ExportDomain.Properties.Settings.Default.SqllhdbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ExportParameterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExportParameterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExportParameterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExportParameterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ExportParameter> ExportParameters
		{
			get
			{
				return this.GetTable<ExportParameter>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExportParameter")]
	public partial class ExportParameter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PrintingEmployeeID;
		
		private int _ReportID;
		
		private System.DateTime _BeginDate;
		
		private System.DateTime _EndDate;
		
		private int _TeamID;
		
		private int _TeamType;
		
		private int _Kam;
		
		private string _KamName;
		
		private bool _Cbx1Checked;
		
		private bool _Cbx2Checked;
		
		private bool _Cbx3Checked;
		
		private bool _Cbx4Checked;
		
		private bool _Cbx5Checked;
		
		private int _JobID;
		
		private int _EstRevID;
		
		private int _QuoteRevID;
		
		private int _WipTaskID;
		
		private int _WorkorderID;
		
		private int _InvoiceID;
		
		private int _CustomerID;
		
		private int _CustomInt1;
		
		private int _CustomInt2;
		
		private string _CustomString1;
		
		private string _CustomString2;
		
		private long _EstItemID;
		
		private int _PrintingEmployeeRoleID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPrintingEmployeeIDChanging(int value);
    partial void OnPrintingEmployeeIDChanged();
    partial void OnReportIDChanging(int value);
    partial void OnReportIDChanged();
    partial void OnBeginDateChanging(System.DateTime value);
    partial void OnBeginDateChanged();
    partial void OnEndDateChanging(System.DateTime value);
    partial void OnEndDateChanged();
    partial void OnTeamIDChanging(int value);
    partial void OnTeamIDChanged();
    partial void OnTeamTypeChanging(int value);
    partial void OnTeamTypeChanged();
    partial void OnKamChanging(int value);
    partial void OnKamChanged();
    partial void OnKamNameChanging(string value);
    partial void OnKamNameChanged();
    partial void OnCbx1CheckedChanging(bool value);
    partial void OnCbx1CheckedChanged();
    partial void OnCbx2CheckedChanging(bool value);
    partial void OnCbx2CheckedChanged();
    partial void OnCbx3CheckedChanging(bool value);
    partial void OnCbx3CheckedChanged();
    partial void OnCbx4CheckedChanging(bool value);
    partial void OnCbx4CheckedChanged();
    partial void OnCbx5CheckedChanging(bool value);
    partial void OnCbx5CheckedChanged();
    partial void OnJobIDChanging(int value);
    partial void OnJobIDChanged();
    partial void OnEstRevIDChanging(int value);
    partial void OnEstRevIDChanged();
    partial void OnQuoteRevIDChanging(int value);
    partial void OnQuoteRevIDChanged();
    partial void OnWipTaskIDChanging(int value);
    partial void OnWipTaskIDChanged();
    partial void OnWorkorderIDChanging(int value);
    partial void OnWorkorderIDChanged();
    partial void OnInvoiceIDChanging(int value);
    partial void OnInvoiceIDChanged();
    partial void OnCustomerIDChanging(int value);
    partial void OnCustomerIDChanged();
    partial void OnCustomInt1Changing(int value);
    partial void OnCustomInt1Changed();
    partial void OnCustomInt2Changing(int value);
    partial void OnCustomInt2Changed();
    partial void OnCustomString1Changing(string value);
    partial void OnCustomString1Changed();
    partial void OnCustomString2Changing(string value);
    partial void OnCustomString2Changed();
    partial void OnEstItemIDChanging(long value);
    partial void OnEstItemIDChanged();
    partial void OnPrintingEmployeeRoleIDChanging(int value);
    partial void OnPrintingEmployeeRoleIDChanged();
    #endregion
		
		public ExportParameter()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintingEmployeeID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PrintingEmployeeID
		{
			get
			{
				return this._PrintingEmployeeID;
			}
			set
			{
				if ((this._PrintingEmployeeID != value))
				{
					this.OnPrintingEmployeeIDChanging(value);
					this.SendPropertyChanging();
					this._PrintingEmployeeID = value;
					this.SendPropertyChanged("PrintingEmployeeID");
					this.OnPrintingEmployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportID", DbType="Int NOT NULL")]
		public int ReportID
		{
			get
			{
				return this._ReportID;
			}
			set
			{
				if ((this._ReportID != value))
				{
					this.OnReportIDChanging(value);
					this.SendPropertyChanging();
					this._ReportID = value;
					this.SendPropertyChanged("ReportID");
					this.OnReportIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginDate", DbType="SmallDateTime NOT NULL")]
		public System.DateTime BeginDate
		{
			get
			{
				return this._BeginDate;
			}
			set
			{
				if ((this._BeginDate != value))
				{
					this.OnBeginDateChanging(value);
					this.SendPropertyChanging();
					this._BeginDate = value;
					this.SendPropertyChanged("BeginDate");
					this.OnBeginDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="SmallDateTime NOT NULL")]
		public System.DateTime EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamID", DbType="Int NOT NULL")]
		public int TeamID
		{
			get
			{
				return this._TeamID;
			}
			set
			{
				if ((this._TeamID != value))
				{
					this.OnTeamIDChanging(value);
					this.SendPropertyChanging();
					this._TeamID = value;
					this.SendPropertyChanged("TeamID");
					this.OnTeamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamType", DbType="Int NOT NULL")]
		public int TeamType
		{
			get
			{
				return this._TeamType;
			}
			set
			{
				if ((this._TeamType != value))
				{
					this.OnTeamTypeChanging(value);
					this.SendPropertyChanging();
					this._TeamType = value;
					this.SendPropertyChanged("TeamType");
					this.OnTeamTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kam", DbType="Int NOT NULL")]
		public int Kam
		{
			get
			{
				return this._Kam;
			}
			set
			{
				if ((this._Kam != value))
				{
					this.OnKamChanging(value);
					this.SendPropertyChanging();
					this._Kam = value;
					this.SendPropertyChanged("Kam");
					this.OnKamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KamName", DbType="NVarChar(50)")]
		public string KamName
		{
			get
			{
				return this._KamName;
			}
			set
			{
				if ((this._KamName != value))
				{
					this.OnKamNameChanging(value);
					this.SendPropertyChanging();
					this._KamName = value;
					this.SendPropertyChanged("KamName");
					this.OnKamNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cbx1Checked", DbType="Bit NOT NULL")]
		public bool Cbx1Checked
		{
			get
			{
				return this._Cbx1Checked;
			}
			set
			{
				if ((this._Cbx1Checked != value))
				{
					this.OnCbx1CheckedChanging(value);
					this.SendPropertyChanging();
					this._Cbx1Checked = value;
					this.SendPropertyChanged("Cbx1Checked");
					this.OnCbx1CheckedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cbx2Checked", DbType="Bit NOT NULL")]
		public bool Cbx2Checked
		{
			get
			{
				return this._Cbx2Checked;
			}
			set
			{
				if ((this._Cbx2Checked != value))
				{
					this.OnCbx2CheckedChanging(value);
					this.SendPropertyChanging();
					this._Cbx2Checked = value;
					this.SendPropertyChanged("Cbx2Checked");
					this.OnCbx2CheckedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cbx3Checked", DbType="Bit NOT NULL")]
		public bool Cbx3Checked
		{
			get
			{
				return this._Cbx3Checked;
			}
			set
			{
				if ((this._Cbx3Checked != value))
				{
					this.OnCbx3CheckedChanging(value);
					this.SendPropertyChanging();
					this._Cbx3Checked = value;
					this.SendPropertyChanged("Cbx3Checked");
					this.OnCbx3CheckedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cbx4Checked", DbType="Bit NOT NULL")]
		public bool Cbx4Checked
		{
			get
			{
				return this._Cbx4Checked;
			}
			set
			{
				if ((this._Cbx4Checked != value))
				{
					this.OnCbx4CheckedChanging(value);
					this.SendPropertyChanging();
					this._Cbx4Checked = value;
					this.SendPropertyChanged("Cbx4Checked");
					this.OnCbx4CheckedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cbx5Checked", DbType="Bit NOT NULL")]
		public bool Cbx5Checked
		{
			get
			{
				return this._Cbx5Checked;
			}
			set
			{
				if ((this._Cbx5Checked != value))
				{
					this.OnCbx5CheckedChanging(value);
					this.SendPropertyChanging();
					this._Cbx5Checked = value;
					this.SendPropertyChanged("Cbx5Checked");
					this.OnCbx5CheckedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobID", DbType="Int NOT NULL")]
		public int JobID
		{
			get
			{
				return this._JobID;
			}
			set
			{
				if ((this._JobID != value))
				{
					this.OnJobIDChanging(value);
					this.SendPropertyChanging();
					this._JobID = value;
					this.SendPropertyChanged("JobID");
					this.OnJobIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstRevID", DbType="Int NOT NULL")]
		public int EstRevID
		{
			get
			{
				return this._EstRevID;
			}
			set
			{
				if ((this._EstRevID != value))
				{
					this.OnEstRevIDChanging(value);
					this.SendPropertyChanging();
					this._EstRevID = value;
					this.SendPropertyChanged("EstRevID");
					this.OnEstRevIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuoteRevID", DbType="Int NOT NULL")]
		public int QuoteRevID
		{
			get
			{
				return this._QuoteRevID;
			}
			set
			{
				if ((this._QuoteRevID != value))
				{
					this.OnQuoteRevIDChanging(value);
					this.SendPropertyChanging();
					this._QuoteRevID = value;
					this.SendPropertyChanged("QuoteRevID");
					this.OnQuoteRevIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WipTaskID", DbType="Int NOT NULL")]
		public int WipTaskID
		{
			get
			{
				return this._WipTaskID;
			}
			set
			{
				if ((this._WipTaskID != value))
				{
					this.OnWipTaskIDChanging(value);
					this.SendPropertyChanging();
					this._WipTaskID = value;
					this.SendPropertyChanged("WipTaskID");
					this.OnWipTaskIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkorderID", DbType="Int NOT NULL")]
		public int WorkorderID
		{
			get
			{
				return this._WorkorderID;
			}
			set
			{
				if ((this._WorkorderID != value))
				{
					this.OnWorkorderIDChanging(value);
					this.SendPropertyChanging();
					this._WorkorderID = value;
					this.SendPropertyChanged("WorkorderID");
					this.OnWorkorderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceID", DbType="Int NOT NULL")]
		public int InvoiceID
		{
			get
			{
				return this._InvoiceID;
			}
			set
			{
				if ((this._InvoiceID != value))
				{
					this.OnInvoiceIDChanging(value);
					this.SendPropertyChanging();
					this._InvoiceID = value;
					this.SendPropertyChanged("InvoiceID");
					this.OnInvoiceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int NOT NULL")]
		public int CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomInt1", DbType="Int NOT NULL")]
		public int CustomInt1
		{
			get
			{
				return this._CustomInt1;
			}
			set
			{
				if ((this._CustomInt1 != value))
				{
					this.OnCustomInt1Changing(value);
					this.SendPropertyChanging();
					this._CustomInt1 = value;
					this.SendPropertyChanged("CustomInt1");
					this.OnCustomInt1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomInt2", DbType="Int NOT NULL")]
		public int CustomInt2
		{
			get
			{
				return this._CustomInt2;
			}
			set
			{
				if ((this._CustomInt2 != value))
				{
					this.OnCustomInt2Changing(value);
					this.SendPropertyChanging();
					this._CustomInt2 = value;
					this.SendPropertyChanged("CustomInt2");
					this.OnCustomInt2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomString1", DbType="NVarChar(500)")]
		public string CustomString1
		{
			get
			{
				return this._CustomString1;
			}
			set
			{
				if ((this._CustomString1 != value))
				{
					this.OnCustomString1Changing(value);
					this.SendPropertyChanging();
					this._CustomString1 = value;
					this.SendPropertyChanged("CustomString1");
					this.OnCustomString1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomString2", DbType="NVarChar(500)")]
		public string CustomString2
		{
			get
			{
				return this._CustomString2;
			}
			set
			{
				if ((this._CustomString2 != value))
				{
					this.OnCustomString2Changing(value);
					this.SendPropertyChanging();
					this._CustomString2 = value;
					this.SendPropertyChanged("CustomString2");
					this.OnCustomString2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstItemID", DbType="BigInt NOT NULL")]
		public long EstItemID
		{
			get
			{
				return this._EstItemID;
			}
			set
			{
				if ((this._EstItemID != value))
				{
					this.OnEstItemIDChanging(value);
					this.SendPropertyChanging();
					this._EstItemID = value;
					this.SendPropertyChanged("EstItemID");
					this.OnEstItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintingEmployeeRoleID", DbType="Int NOT NULL")]
		public int PrintingEmployeeRoleID
		{
			get
			{
				return this._PrintingEmployeeRoleID;
			}
			set
			{
				if ((this._PrintingEmployeeRoleID != value))
				{
					this.OnPrintingEmployeeRoleIDChanging(value);
					this.SendPropertyChanging();
					this._PrintingEmployeeRoleID = value;
					this.SendPropertyChanged("PrintingEmployeeRoleID");
					this.OnPrintingEmployeeRoleIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
