//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SubContractDomain.Model
{
    public partial class SubcontractResponse
    {
        public int ResponseID { get; set; }
        public int SubcontractID { get; set; }
        public int ResponseStatusID { get; set; }
        public Nullable<double> Quotation { get; set; }
        public Nullable<System.DateTime> ScheduleJobDeadline { get; set; }
        public string Remarks { get; set; }
        public int InstallerID { get; set; }
        public string PoNumber { get; set; }
        public Nullable<System.DateTime> PoIssueDate { get; set; }
        public Nullable<System.DateTime> ActualFinishDate { get; set; }
        public Nullable<double> InvoiceAmount { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public int Coordinator { get; set; }
        public bool IsOverBudget { get; set; }
        public bool IsOverBudgetApproved { get; set; }
        public int ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<double> ApprovedBudget { get; set; }
        public bool OverDueWarningIsSent { get; set; }
        public double ExtraCost { get; set; }
        public string ExtraCostRemark { get; set; }
        public Nullable<double> TotalCost { get; set; }
    
        public virtual SubContract SubContract { get; set; }
        public virtual SubContractInstaller SubContractInstaller { get; set; }
        public virtual TblSubcontractStatus TblSubcontractStatu { get; set; }
    }
    
}
