//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SubContractDomain.Model
{
    public partial class SubcontractShipping
    {
        public int ShippingID { get; set; }
        public int SubContractID { get; set; }
        public string Carrier { get; set; }
        public string TrackingNumber { get; set; }
        public string WaybillNote { get; set; }
        public string ShipToName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Postcode { get; set; }
        public string AttnName { get; set; }
        public string AttnPhone { get; set; }
        public string WorkorderNumber { get; set; }
    
        public virtual SubContract SubContract { get; set; }
    }
    
}
