//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SubContractDomain.Model
{
    public partial class SubContractInstaller
    {
        public SubContractInstaller()
        {
            this.SubcontractResponses = new HashSet<SubcontractResponse>();
        }
    
        public int InstallerID { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostCode { get; set; }
        public string Country { get; set; }
        public string ContactName { get; set; }
        public string Position { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Active { get; set; }
        public byte Rate { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<SubcontractResponse> SubcontractResponses { get; set; }
    }
    
}
