//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace SubContractDomain.Model
{
    public partial class SubContractDbEntities : DbContext
    {
        public SubContractDbEntities()
            : base("name=SubContractDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SubcontractCommunication> SubcontractCommunications { get; set; }
        public DbSet<TblSubcontractStatus> TblSubcontractStatus1 { get; set; }
        public DbSet<TblSubcontractRequirement> TblSubcontractRequirements { get; set; }
        public DbSet<SubContract> SubContracts { get; set; }
        public DbSet<SubcontractShipping> SubcontractShippings { get; set; }
        public DbSet<SubContractInstaller> SubContractInstallers { get; set; }
        public DbSet<SubcontractDocument> SubcontractDocuments { get; set; }
        public DbSet<SubcontractItem> SubcontractItems { get; set; }
        public DbSet<SubcontractNote> SubcontractNotes { get; set; }
        public DbSet<SubcontractWorkorder> SubcontractWorkorders { get; set; }
        public DbSet<SubcontractResponse> SubcontractResponses { get; set; }
    }
}
