//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SubContractDomain.Model
{
    public partial class TblSubcontractStatus
    {
        public TblSubcontractStatus()
        {
            this.SubContracts = new HashSet<SubContract>();
            this.SubcontractResponses = new HashSet<SubcontractResponse>();
        }
    
        public int StatusID { get; set; }
        public string StatusConent { get; set; }
        public Nullable<int> CommunicationTypeID { get; set; }
    
        public virtual ICollection<SubContract> SubContracts { get; set; }
        public virtual ICollection<SubcontractResponse> SubcontractResponses { get; set; }
    }
    
}
