//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SubContractDomain.Model
{
    public partial class TblSubcontractRequirement
    {
        public TblSubcontractRequirement()
        {
            this.SubContracts = new HashSet<SubContract>();
        }
    
        public int RequirementID { get; set; }
        public string RequirementContent { get; set; }
        public int Leadtime { get; set; }
        public string Insturction { get; set; }
    
        public virtual ICollection<SubContract> SubContracts { get; set; }
    }
    
}
