//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PermitDomain.Model
{
    public partial class PermitLandlord
    {
        public PermitLandlord()
        {
            this.PermitLandlordContacts = new HashSet<PermitLandlordContact>();
            this.PermitForSignPermits = new HashSet<PermitForSignPermit>();
        }
    
        public int ROWID { get; set; }
        public string NAME { get; set; }
        public string ADDR_1 { get; set; }
        public string ADDR_2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIPCODE { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<PermitLandlordContact> PermitLandlordContacts { get; set; }
        public virtual ICollection<PermitForSignPermit> PermitForSignPermits { get; set; }
    }
    
}
