//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PermitDomain.Model
{
    public partial class PermitTruckType
    {
        public PermitTruckType()
        {
            this.PermitForHoistings = new HashSet<PermitForHoisting>();
        }
    
        public int TruckTypeID { get; set; }
        public string TruckTypeName { get; set; }
        public string TruckWeight { get; set; }
    
        public virtual ICollection<PermitForHoisting> PermitForHoistings { get; set; }
    }
    
}
