//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PermitDomain.Model
{
    public partial class PermitForHoisting
    {
        public int AppID { get; set; }
        public int BaseAppID { get; set; }
        public string TypeOfWork { get; set; }
        public Nullable<System.DateTime> OccupationDate { get; set; }
        public string OccupationTimeStart { get; set; }
        public string OccupationTimeEnd { get; set; }
        public int TypeOfTruck { get; set; }
        public string Tonnage { get; set; }
        public bool DutyCopOnly { get; set; }
        public string ForemanName { get; set; }
        public string ForemanPhone { get; set; }
    
        public virtual PermitBase PermitBase { get; set; }
        public virtual PermitTruckType PermitTruckType { get; set; }
    }
    
}
