//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PermitDomain.Model
{
    public partial class PermitForSignPermit
    {
        public int AppID { get; set; }
        public int BaseAppID { get; set; }
        public int LandlordID { get; set; }
        public int LandlordContactID { get; set; }
        public Nullable<double> NumberOfSigns { get; set; }
        public Nullable<double> ProjectValueEstimated { get; set; }
    
        public virtual PermitBase PermitBase { get; set; }
        public virtual PermitLandlord PermitLandlord { get; set; }
        public virtual PermitLandlordContact PermitLandlordContact { get; set; }
    }
    
}
