//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PermitDomain.Model
{
    public partial class PermitDocument
    {
        public int DocID { get; set; }
        public int BaseAppID { get; set; }
        public string DocTitle { get; set; }
        public string DocHyperlink { get; set; }
        public int UploadBy { get; set; }
        public Nullable<System.DateTime> UploadAt { get; set; }
        public int DocType { get; set; }
        public string Remark { get; set; }
        public bool IsFinal { get; set; }
    
        public virtual PermitBase PermitBase { get; set; }
        public virtual PermitDocumentType PermitDocumentType { get; set; }
    }
    
}
