//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PermitDomain.Model
{
    public partial class PermitLandlordContact
    {
        public PermitLandlordContact()
        {
            this.PermitForSignPermits = new HashSet<PermitForSignPermit>();
        }
    
        public int CONTACT_ID { get; set; }
        public int ROWID { get; set; }
        public string CONTACT_FIRST_NAME { get; set; }
        public string CONTACT_LAST_NAME { get; set; }
        public string CONTACT_POSITION { get; set; }
        public string CONTACT_HONORIFIC { get; set; }
        public string CONTACT_PHONE { get; set; }
        public string CONTACT_FAX { get; set; }
        public string CONTACT_MOBILE { get; set; }
        public string CONTACT_EMAIL { get; set; }
        public bool CONTACT_ACTIVE { get; set; }
    
        public virtual PermitLandlord PermitLandlord { get; set; }
        public virtual ICollection<PermitForSignPermit> PermitForSignPermits { get; set; }
    }
    
}
