//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace PermitDomain.Model
{
    public partial class PermitDbEntities : DbContext
    {
        public PermitDbEntities()
            : base("name=PermitDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PermitDocument> PermitDocuments { get; set; }
        public DbSet<PermitLandlord> PermitLandlords { get; set; }
        public DbSet<PermitLandlordContact> PermitLandlordContacts { get; set; }
        public DbSet<PermitRequirement> PermitRequirements { get; set; }
        public DbSet<PermitStatu> PermitStatus { get; set; }
        public DbSet<PermitBase> PermitBases { get; set; }
        public DbSet<PermitForSignPermit> PermitForSignPermits { get; set; }
        public DbSet<PermitDocumentType> PermitDocumentTypes { get; set; }
        public DbSet<PermitForStakeout> PermitForStakeouts { get; set; }
        public DbSet<PermitForHoisting> PermitForHoistings { get; set; }
        public DbSet<PermitTruckType> PermitTruckTypes { get; set; }
        public DbSet<PermitCommunication> PermitCommunications { get; set; }
        public DbSet<PermitForSignVariance> PermitForSignVariances { get; set; }
    }
}
