//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PermitDomain.Model
{
    public partial class PermitBase
    {
        public PermitBase()
        {
            this.PermitDocuments = new HashSet<PermitDocument>();
            this.PermitForSignPermits = new HashSet<PermitForSignPermit>();
            this.PermitForStakeouts = new HashSet<PermitForStakeout>();
            this.PermitForHoistings = new HashSet<PermitForHoisting>();
            this.PermitCommunications = new HashSet<PermitCommunication>();
            this.PermitForSignVariances = new HashSet<PermitForSignVariance>();
        }
    
        public int BaseAppID { get; set; }
        public int JobID { get; set; }
        public string JobNumber { get; set; }
        public string JobTitle { get; set; }
        public string Description { get; set; }
        public int RequirementID { get; set; }
        public int RequestNumber { get; set; }
        public int RequestBy { get; set; }
        public System.DateTime RequestDate { get; set; }
        public short Version { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public int InstallToCustomerID { get; set; }
        public string Remark { get; set; }
        public string ReviseReason { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
        public string ResponseRemark1 { get; set; }
        public string ResponseRemark2 { get; set; }
    
        public virtual PermitRequirement PermitRequirement { get; set; }
        public virtual PermitStatu PermitStatu { get; set; }
        public virtual ICollection<PermitDocument> PermitDocuments { get; set; }
        public virtual ICollection<PermitForSignPermit> PermitForSignPermits { get; set; }
        public virtual ICollection<PermitForStakeout> PermitForStakeouts { get; set; }
        public virtual ICollection<PermitForHoisting> PermitForHoistings { get; set; }
        public virtual ICollection<PermitCommunication> PermitCommunications { get; set; }
        public virtual ICollection<PermitForSignVariance> PermitForSignVariances { get; set; }
    }
    
}
