//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PermitDomain.Model
{
    public partial class PermitDocumentType
    {
        public PermitDocumentType()
        {
            this.PermitDocuments = new HashSet<PermitDocument>();
        }
    
        public int TypeID { get; set; }
        public string TypeName { get; set; }
        public int SelectTypeID { get; set; }
        public int PermitType { get; set; }
    
        public virtual ICollection<PermitDocument> PermitDocuments { get; set; }
    }
    
}
